import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import vm from 'node:vm';
import ts from 'typescript';
const resources=JSON.parse(fs.readFileSync('data/agent-library-resources.json'));
const agents=JSON.parse(fs.readFileSync('data/agent-library-packages.json'));
function load(file,deps={},globals={}){const exports={};vm.runInNewContext(ts.transpileModule(fs.readFileSync(file,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022,esModuleInterop:true,jsx:ts.JsxEmit.ReactJSX}}).outputText,{exports,require:n=>{if(n in deps)return deps[n];throw Error(n)},Response,URL,...globals});return exports;}
function signer({data=resources,isPublic=false}={}){const signed=[];let clients=0;return {signed,clients:()=>clients,...load('lib/agent-library-files.ts',{'@/data/agent-library-packages.json':agents,'@/data/agent-library-resources.json':data,'@/lib/supabase/admin':{createSupabaseAdminClient:()=>{clients++;return {storage:{getBucket:async()=>({data:{public:isPublic}}),from:bucket=>({createSignedUrl:async(path,ttl,options)=>{signed.push({bucket,path,ttl,options});return {data:{signedUrl:'https://signed.example/'+path}};}})}};}}})};}
for(const resource of resources.resources)test(`resource ${resource.slug}: correct private file and attachment`,async()=>{const s=signer();assert.equal(await s.getAgentDownloadUrl(resource.slug),'https://signed.example/'+resource.version+'/'+resource.filename);assert.equal(s.signed.length,1);const [call]=s.signed;assert.equal(call.bucket,'agent-library-private');assert.equal(call.ttl,120);assert.equal(call.options.download,resource.filename);assert.ok(resource.size_bytes>0);assert.match(resource.sha256,/^[a-f0-9]{64}$/);});
for(const resource of resources.resources)test(`resource ${resource.slug}: public bucket is refused`,async()=>{const s=signer({isPublic:true});await assert.rejects(s.getAgentDownloadUrl(resource.slug));assert.equal(s.signed.length,0);});
for(const [slug,filename] of [['full-kit','../kit.zip'],['setup-prompt','prompt.html'],['setup-prompt','../prompt.txt'],['full-kit','kit.txt']])test(`unsafe resource filename refused: ${slug} ${filename}`,async()=>{const s=signer({data:{resources:[{slug,version:'2.2.1',filename}]}});await assert.rejects(s.getAgentDownloadUrl(slug));assert.equal(s.clients(),0)});
test('unknown resource never initializes privileged storage',async()=>{const s=signer();assert.equal(await s.getAgentDownloadUrl('not-a-resource'),null);assert.equal(s.clients(),0)});
for(const r of resources.resources)test(`owner upload supports ${r.slug}`,async()=>{let signed;const route=load('app/api/admin/agent-library/upload/route.ts',{'@/data/agent-library-packages.json':agents,'@/data/agent-library-resources.json':resources,'@/lib/auth/session':{getCurrentAuth:async()=>({user:{id:'owner'},adminRole:'owner'})},'@/lib/supabase/admin':{createSupabaseAdminClient:()=>({storage:{getBucket:async()=>({data:{public:false}}),from:()=>({createSignedUploadUrl:async(path,options)=>{signed={path,options};return {data:{signedUrl:'https://signed.example/upload'}};}})}})}});const response=await route.POST(new Request('https://example.test/api/admin/agent-library/upload',{method:'POST',headers:{Origin:'https://example.test','Content-Type':'application/json'},body:JSON.stringify({slug:r.slug,action:'upload'})}));assert.equal(response.status,200);assert.equal(signed.path,r.version+'/'+r.filename);assert.equal(signed.options.upsert,false);});
function ui({response={ok:true,json:async()=>({url:'https://signed.example/file'})}}={}){const calls=[],locations=[],states=[];let index=0;const jsx=(type,props)=>({type,props});const react={useState:initial=>{const i=index++;states[i]=initial;return [initial,value=>{states[i]=value}]},useRef:()=>({current:null})};const catalog=load('components/agent-library/catalog.ts');const mod=load('components/agent-library/agent-library.tsx',{'react':react,'react/jsx-runtime':{jsx,jsxs:jsx},'next/link':{default:'a'},'./catalog':catalog,'./agent-library.css':{}},{fetch:async(...args)=>{calls.push(args);return response;},window:{location:{assign:value=>locations.push(value)}}});const root=mod.AgentLibrary();const nodes=[];function visit(v){if(!v)return;if(Array.isArray(v)){v.forEach(visit);return;}if(typeof v==='object'){nodes.push(v);visit(v.props?.children)}}visit(root);return {nodes,calls,locations,states};}
for(const [label,slug] of [['Tải toàn bộ bộ kit','full-kit'],['Tải prompt mẫu','setup-prompt']])test(`UI button ${label} uses protected download then navigation`,async()=>{const u=ui();const btn=u.nodes.find(x=>x.type==='button'&&Array.isArray(x.props.children)&&x.props.children.includes(label));assert.ok(btn);assert.equal(btn.props.disabled,false);await btn.props.onClick();assert.equal(u.calls[0][0],`/api/agent-library/${slug}/download?format=json`);assert.equal(u.calls[0][1].cache,'no-store');assert.deepEqual(u.locations,['https://signed.example/file']);});
test('UI displays download failure and does not navigate',async()=>{const u=ui({response:{ok:false,json:async()=>({message:'Bạn cần đăng nhập.'})}});await u.nodes.find(x=>x.type==='button'&&x.props.className==='kit-download').props.onClick();assert.equal(u.locations.length,0);assert.ok(u.states.includes('Bạn cần đăng nhập.'));});
test('prompt is a resource card; all ten Agent cards remain',()=>{const u=ui();assert.equal(u.nodes.filter(n=>n.type==='article'&&n.props.className==='card').length,10);assert.equal(u.nodes.filter(n=>n.type==='article'&&n.props.className==='card prompt-card').length,1);});
test('full download stays aligned with all ten released Agent packages',()=>{const full=resources.resources.find(r=>r.slug==='full-kit');assert.equal(resources.resources.length,2);assert.equal(new Set(resources.resources.map(r=>r.slug)).size,2);for(const agent of agents.agents){assert.equal(full.version,agent.version);assert.equal(full.sha256,agent.source_release_sha256);}assert.equal(resources.resources.find(r=>r.slug==='setup-prompt').version,agents.version);});
