import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import vm from 'node:vm';
import ts from 'typescript';
function load(file, deps = {}) { const exports = {}; vm.runInNewContext(ts.transpileModule(fs.readFileSync(file, 'utf8'), {compilerOptions:{module:ts.ModuleKind.CommonJS,jsx:ts.JsxEmit.ReactJSX}}).outputText, {exports,require:name=>{if(name in deps)return deps[name];throw Error(name)}});return exports; }
const catalog=load('components/agent-library/tutorial-videos.ts');
function ui(){const states=[];let index=0;const jsx=(type,props)=>({type,props});const component= load('components/agent-library/video-tutorials.tsx',{'./tutorial-videos':catalog,react:{useState:value=>{const slot=index++;if(!(slot in states))states[slot]=value;return [states[slot],next=>states[slot]=next];}},'react/jsx-runtime':{jsx,jsxs:jsx}});return ()=>{index=0;const nodes=[];function walk(v){if(Array.isArray(v))return v.forEach(walk);if(v&&typeof v==='object'){nodes.push(v);walk(v.props?.children)}}walk(component.VideoTutorials());return nodes;};}
test('video player loads only on intent, switches every lesson and has no external YouTube link',()=>{const render=ui();let nodes=render();assert.equal(nodes.filter(n=>n.type==='iframe').length,0);nodes.find(n=>n.props?.className==='video-start').props.onClick();nodes=render();assert.match(nodes.find(n=>n.type==='iframe').props.src,/-rwOJpzlIuk/);for(const [index,video] of catalog.tutorialVideos.entries()){nodes.filter(n=>n.type==='button'&&n.props.className?.startsWith('video-lesson'))[index].props.onClick();nodes=render();const frames=nodes.filter(n=>n.type==='iframe');assert.equal(frames.length,1);assert.equal(frames[0].props.title,video.title);assert.equal(frames[0].props.src,`https://www.youtube-nocookie.com/embed/${video.youtubeId}?rel=0&autoplay=1`);assert.equal(frames[0].props.referrerPolicy,'strict-origin-when-cross-origin');assert.equal(nodes.filter(n=>n.type==='a').length,0);assert.equal(nodes.filter(n=>n.props?.['aria-current']==='true').length,1);}});
test('all supplied videos retain exact order, unique IDs and sublesson 5.1',()=>{assert.equal(catalog.tutorialVideos.map(v=>v.youtubeId).join(','),'-rwOJpzlIuk,hazaF7LyCYE,YkH_DGEyAQ0,3YElsi_Steo,d_aD5vAbWDE,_w8zKfdsI8E,3TKUNWQLTj8,LLehWLFiBEA,430SgTfi6ck,S4nDl4L5ZnE,PedB4fDH02Y');assert.equal(catalog.tutorialVideos[5].number,'5.1');});

test('previous and next traverse every lesson, stop at boundaries and update materials heading',()=>{const render=ui();let nodes=render();const navigation=()=>nodes.find(n=>n.props?.className==='video-navigation').props.children;assert.equal(navigation()[0].props.disabled,true);for(let i=1;i<catalog.tutorialVideos.length;i++){navigation()[2].props.onClick();nodes=render();assert.equal(nodes.find(n=>n.type==='iframe').props.title,catalog.tutorialVideos[i].title);assert.equal(nodes.find(n=>n.type==='h4').props.children[1],catalog.tutorialVideos[i].number);}assert.equal(navigation()[2].props.disabled,true);navigation()[2].props.onClick();nodes=render();assert.equal(nodes.find(n=>n.type==='iframe').props.title,catalog.tutorialVideos.at(-1).title);for(let i=catalog.tutorialVideos.length-2;i>=0;i--){navigation()[0].props.onClick();nodes=render();assert.equal(nodes.find(n=>n.type==='iframe').props.title,catalog.tutorialVideos[i].title);}assert.equal(navigation()[0].props.disabled,true);});
