import type {
  CrmContact,
  CrmDashboardData,
  CrmEmailCampaignRow,
  CrmEvent,
  CrmReportAttributionRow,
  CrmSegmentRow,
  CrmAutomationWorkflowRow,
  CrmIntegrationRow,
  CrmLeadRow,
  CrmOrderRow,
  CrmStudentRow,
  CrmTeamMember,
  KpiMetric,
} from "./types";

export const crmStageLabels = {
  new: "Mới",
  not_contacted: "Chưa liên hệ",
  consulting: "Đang tư vấn",
  high_intent: "Quan tâm cao",
  pending_payment: "Chờ thanh toán",
  paid: "Đã thanh toán",
  disqualified: "Không phù hợp",
} as const;

export const demoKpis: KpiMetric[] = [
  { label: "Lead mới hôm nay", value: "38", delta: "+12%", tone: "blue", series: [12, 16, 15, 24, 22, 31, 38] },
  { label: "MQL", value: "124", delta: "+8%", tone: "purple", series: [40, 52, 61, 76, 88, 106, 124] },
  { label: "Đã thanh toán", value: "29", delta: "+5", tone: "green", series: [8, 11, 13, 15, 21, 24, 29] },
  { label: "Doanh thu 30 ngày", value: "186,4tr", delta: "+18%", tone: "green", series: [90, 112, 118, 124, 143, 166, 186] },
  { label: "Doanh thu từ email", value: "42,8tr", delta: "+11%", tone: "orange", series: [12, 18, 21, 20, 31, 36, 43] },
  { label: "Automation đang chạy", value: "7", delta: "2 flow mới", tone: "purple", series: [2, 3, 4, 4, 5, 6, 7] },
];

export const demoLeads: CrmLeadRow[] = [
  {
    id: "lead_demo_1",
    contactId: "contact_demo_1",
    name: "Minh Anh",
    email: "minh***@gmail.com",
    phone: "+8490***567",
    source: "Facebook Ads",
    course: "Facebook Ads Master 2026",
    leadScore: 86,
    owner: "T. Anh",
    stage: "pending_payment",
    emailStatus: "clicked",
    lastTouch: "12 phút trước",
    nextAction: "Nhắc thanh toán",
    potentialValue: 799000,
    createdAt: "2026-06-15T09:18:00Z",
    tags: ["hot", "ads"],
  },
  {
    id: "lead_demo_2",
    contactId: "contact_demo_2",
    name: "Hoàng Nam",
    email: "nam***@gmail.com",
    phone: "+8493***351",
    source: "Website",
    course: "AI Growth OS",
    leadScore: 62,
    owner: "Sale A",
    stage: "consulting",
    emailStatus: "opened",
    lastTouch: "1 giờ trước",
    nextAction: "Gọi tư vấn",
    potentialValue: 1299000,
    createdAt: "2026-06-15T08:04:00Z",
    tags: ["mql", "ai-growth"],
  },
  {
    id: "lead_demo_3",
    contactId: "contact_demo_3",
    name: "Phương Thảo",
    email: "thao***@gmail.com",
    phone: "+8485***283",
    source: "Admin access",
    course: "Facebook Ads Master 2026",
    leadScore: 94,
    owner: "CSKH",
    stage: "paid",
    emailStatus: "delivered",
    lastTouch: "3 giờ trước",
    nextAction: "Onboard học viên",
    potentialValue: 799000,
    createdAt: "2026-06-15T06:44:00Z",
    tags: ["paid", "student"],
  },
  {
    id: "lead_demo_4",
    contactId: "contact_demo_4",
    name: "Quỳnh Mai",
    email: "mai***@company.vn",
    phone: "+8498***019",
    source: "Zalo",
    course: "Bộ Agent Kit X10",
    leadScore: 48,
    owner: "Sale B",
    stage: "not_contacted",
    emailStatus: "sent",
    lastTouch: "Hôm qua",
    nextAction: "Gọi lần 1",
    potentialValue: 799000,
    createdAt: "2026-06-14T16:30:00Z",
    tags: ["new"],
  },
  {
    id: "lead_demo_5",
    contactId: "contact_demo_5",
    name: "Gia Huy",
    email: "huy***@gmail.com",
    phone: "+8491***888",
    source: "Email",
    course: "Ebook Facebook Ads",
    leadScore: 32,
    owner: "Sale A",
    stage: "new",
    emailStatus: "unopened",
    lastTouch: "2 ngày trước",
    nextAction: "Follow-up email",
    potentialValue: 299000,
    createdAt: "2026-06-13T10:12:00Z",
    tags: ["ebook"],
  },
];

export const demoOrders: CrmOrderRow[] = [
  {
    id: "order_demo_1",
    orderCode: "TAMM-DEMO-799",
    contactId: "contact_demo_1",
    customer: "Minh Anh",
    product: "Facebook Ads Master 2026",
    value: 799000,
    discount: 0,
    payment: "SePay",
    status: "pending",
    source: "Facebook",
    owner: "Sale A",
    created: "15/06",
    due: "16/06",
  },
  {
    id: "order_demo_2",
    orderCode: "TAMM-DEMO-1299",
    contactId: "contact_demo_2",
    customer: "Hoàng Nam",
    product: "AI Growth OS",
    value: 1299000,
    discount: 0,
    payment: "Manual",
    status: "paid",
    source: "Website",
    owner: "T. Anh",
    created: "15/06",
    due: "-",
  },
  {
    id: "order_demo_3",
    orderCode: "TAMM-DEMO-299",
    contactId: "contact_demo_5",
    customer: "Gia Huy",
    product: "Ebook Facebook Ads",
    value: 299000,
    discount: 0,
    payment: "SePay",
    status: "paid",
    source: "Email",
    owner: "Ops",
    created: "14/06",
    due: "-",
  },
];

export const demoStudents: CrmStudentRow[] = [
  {
    id: "student_demo_1",
    contactId: "contact_demo_3",
    student: "Phương Thảo",
    course: "Facebook Ads Master 2026",
    status: "active",
    progress: "68%",
    lastLearned: "Hôm nay",
    engagement: "Cao",
    upsell: "AI Agent",
    owner: "CSKH",
    emailCare: "delivered",
  },
  {
    id: "student_demo_2",
    contactId: "contact_demo_2",
    student: "Hoàng Nam",
    course: "AI Growth OS",
    status: "active",
    progress: "24%",
    lastLearned: "Hôm qua",
    engagement: "Vừa",
    upsell: "Coaching",
    owner: "CSKH",
    emailCare: "opened",
  },
  {
    id: "student_demo_3",
    contactId: "contact_demo_5",
    student: "Gia Huy",
    course: "Ebook Facebook Ads",
    status: "inactive",
    progress: "12%",
    lastLearned: "15 ngày",
    engagement: "Thấp",
    upsell: "-",
    owner: "Ops",
    emailCare: "pending",
  },
];

export const demoTeamMembers: CrmTeamMember[] = [
  {
    id: "team_member_1",
    member: "The Anh",
    role: "owner",
    pipeline: "86 leads",
    tasks: "12",
    sla: "99%",
    status: "active",
  },
  {
    id: "team_member_2",
    member: "Sale A",
    role: "sales",
    pipeline: "142 leads",
    tasks: "31",
    sla: "94%",
    status: "active",
  },
  {
    id: "team_member_3",
    member: "CSKH",
    role: "student-success",
    pipeline: "64 students",
    tasks: "18",
    sla: "91%",
    status: "active",
  },
];

export const demoIntegrations: CrmIntegrationRow[] = [
  {
    id: "integration_resend",
    provider: "Resend",
    type: "Email",
    status: "mock/live by env",
    lastSync: "Webhook ready",
    health: "ready",
  },
  {
    id: "integration_meta_capi",
    provider: "Meta CAPI",
    type: "Ads event",
    status: "placeholder",
    lastSync: "Chưa bật",
    health: "mock",
  },
  {
    id: "integration_google_enhanced",
    provider: "Google Enhanced Conversions",
    type: "Ads event",
    status: "placeholder",
    lastSync: "Chưa bật",
    health: "mock",
  },
  {
    id: "integration_tiktok",
    provider: "TikTok Events API",
    type: "Ads event",
    status: "placeholder",
    lastSync: "Chưa bật",
    health: "mock",
  },
];

export const demoSegments: CrmSegmentRow[] = [
  {
    id: "segment_demo_1",
    name: "Lead nóng Facebook Ads",
    condition: "score >= 50 AND tag ads",
    size: 186,
    goal: "Chốt 799K",
    channel: "Email + Sale",
    updated: "15/06",
    status: "active",
  },
  {
    id: "segment_demo_2",
    name: "Chờ thanh toán 48h",
    condition: "stage = pending_payment",
    size: 74,
    goal: "Thu hồi thanh toán",
    channel: "Email + Zalo",
    updated: "15/06",
    status: "active",
  },
  {
    id: "segment_demo_3",
    name: "Học viên inactive",
    condition: "last_seen > 14 ngày",
    size: 39,
    goal: "Giữ chân",
    channel: "CSKH",
    updated: "14/06",
    status: "draft",
  },
];

export const demoAutomationWorkflows: CrmAutomationWorkflowRow[] = [
  {
    id: "automation_demo_1",
    name: "Lead form -> 3 email",
    status: "active",
    runs: "186 runs",
    runsNumeric: 186,
    updated: "15/06",
  },
  {
    id: "automation_demo_2",
    name: "Pending payment rescue",
    status: "active",
    runs: "74 runs",
    runsNumeric: 74,
    updated: "15/06",
  },
];

export const demoReportAttributionRows: CrmReportAttributionRow[] = [
  {
    id: "report_demo_1",
    channel: "Facebook Ads",
    leads: 420,
    mql: 186,
    paid: 52,
    cr: "12.4%",
    revenue: 94200000,
    cac: "96K",
    roi: "4.1x",
    emailRevenue: 18400000,
    note: "Best for 799K",
  },
  {
    id: "report_demo_2",
    channel: "Website Organic",
    leads: 210,
    mql: 88,
    paid: 31,
    cr: "14.8%",
    revenue: 41200000,
    cac: "0",
    roi: "n/a",
    emailRevenue: 9200000,
    note: "High intent",
  },
  {
    id: "report_demo_3",
    channel: "Email",
    leads: 96,
    mql: 52,
    paid: 18,
    cr: "18.7%",
    revenue: 42800000,
    cac: "12K",
    roi: "9.3x",
    emailRevenue: 42800000,
    note: "Cart recovery",
  },
];

export const demoEvents: CrmEvent[] = [
  { id: "evt_1", type: "checkout_click", title: "Click checkout Facebook Ads 2026", description: "+20 điểm lead score", occurredAt: "12 phút trước", tone: "blue" },
  { id: "evt_2", type: "email_click", title: "Click email remarketing", description: "CTA: Nhận hướng dẫn thanh toán", occurredAt: "35 phút trước", tone: "purple" },
  { id: "evt_3", type: "order_created", title: "Tạo đơn chờ thanh toán", description: "TAMM-demo-799K", occurredAt: "1 giờ trước", tone: "orange" },
  { id: "evt_4", type: "note", title: "Sale note", description: "Quan tâm gói 799K có support", occurredAt: "2 giờ trước", tone: "slate" },
];

export const demoEmailCampaigns: CrmEmailCampaignRow[] = [
  {
    id: "email_campaign_demo_1",
    name: "Cart recovery 799K",
    segment: "Chờ thanh toán 48h",
    type: "Drip",
    status: "active",
    sendTime: "Realtime",
    openRate: "64%",
    clickRate: "31%",
    conversion: "8.4%",
    revenue: 42800000,
    owner: "Ops",
  },
  {
    id: "email_campaign_demo_2",
    name: "Ebook preorder",
    segment: "Ebook lead",
    type: "Broadcast",
    status: "scheduled",
    sendTime: "16/06 08:00",
    openRate: "42%",
    clickRate: "13%",
    conversion: "3.2%",
    revenue: 17100000,
    owner: "T. Anh",
  },
  {
    id: "email_campaign_demo_3",
    name: "Student upsell",
    segment: "Học viên active",
    type: "A/B Test",
    status: "draft",
    sendTime: "Chưa đặt",
    openRate: "-",
    clickRate: "-",
    conversion: "-",
    revenue: 0,
    owner: "CSKH",
  },
];

export const demoEmailKpis: KpiMetric[] = [
  { label: "Email đã gửi", value: "18.420", tone: "blue", series: [400, 800, 1200, 2100, 3200] },
  { label: "Open rate", value: "46%", tone: "purple", series: [28, 34, 39, 42, 46] },
  { label: "Click rate", value: "18%", tone: "green", series: [8, 10, 12, 16, 18] },
  { label: "Doanh thu từ email", value: "42,8tr", tone: "green", series: [12, 18, 24, 36, 43] },
  { label: "Email chưa mở cần follow-up", value: "1.208", tone: "orange", series: [1500, 1420, 1320, 1260, 1208] },
  { label: "A/B test đang chạy", value: "2", tone: "purple", series: [0, 1, 1, 2, 2] },
];

export const demoContacts: CrmContact[] = demoLeads.map((lead) => ({
  id: lead.contactId,
  fullName: lead.name,
  email: lead.email,
  phone: lead.phone,
  source: lead.source,
  ownerName: lead.owner,
  lifecycleStage: lead.stage === "paid" ? "student" : "lead",
  leadScore: lead.leadScore,
  tags: lead.tags,
  courses: [lead.course],
  marketingConsent: lead.emailStatus !== "unsubscribed",
}));

export const demoDashboard: CrmDashboardData = {
  kpis: demoKpis,
  funnel: [
    { label: "Lead", value: 820, tone: "blue" },
    { label: "MQL", value: 312, tone: "purple" },
    { label: "Tư vấn", value: 168, tone: "orange" },
    { label: "Chờ TT", value: 74, tone: "orange" },
    { label: "Paid", value: 48, tone: "green" },
  ],
  revenue: [
    { label: "T2", value: 22 },
    { label: "T3", value: 31 },
    { label: "T4", value: 28 },
    { label: "T5", value: 46 },
    { label: "T6", value: 58 },
    { label: "T7", value: 64 },
    { label: "CN", value: 71 },
  ],
  sources: [
    { label: "Facebook", value: 44, tone: "blue" },
    { label: "Website", value: 22, tone: "green" },
    { label: "Email", value: 18, tone: "purple" },
    { label: "Zalo", value: 16, tone: "orange" },
  ],
  emailPerformance: [
    { label: "Broadcast", open: 42, click: 16 },
    { label: "Drip", open: 51, click: 22 },
    { label: "Cart", open: 64, click: 31 },
  ],
  activity: demoEvents,
  tasks: [
    { title: "Gọi lại lead chờ thanh toán", owner: "Sale A", due: "Hôm nay", tone: "orange" },
    { title: "Gắn tag học viên inactive", owner: "CSKH", due: "Mai", tone: "purple" },
    { title: "Kiểm tra bounce email", owner: "Ops", due: "2 ngày", tone: "red" },
  ],
  campaigns: [
    { name: "Cart recovery 799K", status: "Cần xem", metric: "CR 8,4%" },
    { name: "Ebook preorder follow-up", status: "Đang chạy", metric: "OR 44%" },
  ],
  workflows: [
    { name: "Lead form -> 3 email", status: "Live", runs: "186 runs" },
    { name: "Pending payment rescue", status: "Live", runs: "74 runs" },
  ],
  courses: [
    { name: "Facebook Ads Master 2026", revenue: "94,2tr", paid: 118 },
    { name: "Bộ Agent Kit X10", revenue: "41,5tr", paid: 52 },
    { name: "Ebook Facebook Ads", revenue: "17,1tr", paid: 57 },
  ],
};
