"use client";

import { Archive, ArrowDown, ArrowLeft, ArrowUp, BookOpen, Check, ChevronRight, FileText, Layers3, Pencil, Plus, Search, Settings, Trash2, Upload, Users, Video } from "lucide-react";
import Link from "next/link";
import Image from "next/image";
import { useRouter, useSearchParams } from "next/navigation";
import { useEffect, useRef, useState, useTransition, type ReactNode } from "react";
import { AdminDialog } from "@/components/admin/admin-dialog";
import { createSupabaseBrowserClient } from "@/lib/supabase/client";
import { uploadMediaFile } from "@/lib/supabase/media-upload";
import { toYouTubeEmbedUrl } from "@/lib/youtube";
import type { AdminLmsSnapshot, LmsCourse, LmsLesson, LmsModule, LmsResource } from "@/lib/lms/types";

type ActionPayload = Record<string, unknown> & { action: string };
type SubmitAction = (payload: ActionPayload) => Promise<boolean>;
type Tab = "curriculum" | "resources" | "students" | "settings";
type Editor = { kind: "module"; module?: LmsModule } | { kind: "lesson"; lesson?: LmsLesson; moduleId: string } | { kind: "resource"; resource?: LmsResource } | null;
const tabs = [{ id: "curriculum", label: "Nội dung khóa học", icon: Layers3 }, { id: "resources", label: "Tài liệu", icon: FileText }, { id: "students", label: "Học viên", icon: Users }, { id: "settings", label: "Thông tin & xuất bản", icon: Settings }] as const;
const states = [["draft", "Bản nháp"], ["published", "Đang xuất bản"], ["archived", "Đã lưu trữ"]] as const;
const inputClass = "min-h-10 w-full rounded-lg border border-slate-200 bg-white px-3 py-2 text-sm text-slate-900 outline-none focus:border-blue-500 focus:ring-2 focus:ring-blue-100 disabled:bg-slate-50";
const primaryClass = "inline-flex min-h-10 items-center justify-center gap-2 rounded-lg bg-blue-600 px-3 text-sm font-semibold text-white hover:bg-blue-700 disabled:opacity-50";
const secondaryClass = "inline-flex min-h-10 items-center justify-center gap-2 rounded-lg border border-slate-200 bg-white px-3 text-sm font-medium text-slate-700 hover:bg-slate-50 disabled:opacity-40";
function allResources(course: LmsCourse) { return [...new Map([...course.resources, ...course.modules.flatMap((module) => module.lessons.flatMap((lesson) => lesson.resources))].map((resource) => [resource.id, resource])).values()]; }
const get = (data: FormData, key: string) => String(data.get(key) ?? "").trim();
function normalizedTab(value: string | null): Tab { if (value === "media" || value === "resources") return "resources"; if (value === "students" || value === "analytics") return "students"; if (value === "sales" || value === "publish" || value === "settings") return "settings"; return "curriculum"; }
function statusLabel(status: string) { return states.find(([key]) => key === status)?.[1] ?? ({ active: "Đang học", completed: "Hoàn thành", paused: "Tạm dừng", revoked: "Đã thu quyền" } as Record<string, string>)[status] ?? status; }
function Badge({ status }: { status: string }) { return <span className={`inline-flex shrink-0 rounded-full px-2 py-1 text-xs font-medium ${status === "published" || status === "active" ? "bg-emerald-50 text-emerald-700" : status === "draft" ? "bg-amber-50 text-amber-700" : "bg-slate-100 text-slate-600"}`}>{statusLabel(status)}</span>; }
function Field({ label, hint, children }: { label: string; hint?: string; children: ReactNode }) { return <label className="grid min-w-0 gap-1.5 text-sm font-medium text-slate-700"><span>{label}</span>{children}{hint ? <span className="text-xs font-normal leading-5 text-slate-500">{hint}</span> : null}</label>; }
function Notice({ message, error = false }: { message: string; error?: boolean }) { return message ? <p role={error ? "alert" : "status"} className={`rounded-lg border px-3 py-2 text-sm ${error ? "border-red-200 bg-red-50 text-red-700" : "border-emerald-200 bg-emerald-50 text-emerald-700"}`}>{message}</p> : null; }
function Empty({ children }: { children: ReactNode }) { return <div className="grid min-h-48 place-items-center p-8 text-center text-sm leading-6 text-slate-500">{children}</div>; }
function StatusSelect({ status = "draft" }: { status?: string }) { return <select className={inputClass} name="status" defaultValue={status}>{states.map(([key, label]) => <option value={key} key={key}>{label}</option>)}</select>; }

/** Each editor stays mounted on failure; closing a changed draft requires an explicit choice. */
function EditorDialog({ title, onClose, busy, error, children, onSubmit }: { title: string; onClose: () => void; busy: boolean; error: string; children: ReactNode; onSubmit: (data: FormData) => void }) {
  const [dirty, setDirty] = useState(false);
  const [discard, setDiscard] = useState(false);
  return <AdminDialog open onClose={() => { if (!busy) { if (dirty) setDiscard(true); else onClose(); } }} title={discard ? "Bỏ các thay đổi chưa lưu?" : title} wide>
    <div hidden={!discard} className="space-y-4"><p className="text-sm text-slate-600">Các thay đổi trong cửa sổ này chưa được lưu.</p><div className="flex justify-end gap-2"><button type="button" onClick={() => setDiscard(false)} className={secondaryClass}>Tiếp tục sửa</button><button type="button" onClick={onClose} className="rounded-lg bg-red-600 px-4 py-2 text-sm font-semibold text-white">Bỏ thay đổi</button></div></div><form hidden={discard} onChange={() => setDirty(true)} onSubmit={(event) => { event.preventDefault(); onSubmit(new FormData(event.currentTarget)); }} className="mx-auto max-w-3xl space-y-4">
      <fieldset disabled={busy} className="min-w-0 space-y-4">{children}</fieldset>
      <Notice message={error} error />
      <footer className="sticky bottom-0 flex items-center justify-between gap-3 border-t border-slate-200 bg-white py-3"><span className="text-xs text-slate-500">{busy ? "Đang lưu thay đổi…" : dirty ? "Có thay đổi chưa lưu" : ""}</span><div className="flex gap-2"><button type="button" disabled={busy} className={secondaryClass} onClick={() => dirty ? setDiscard(true) : onClose()}>Hủy</button><button type="submit" disabled={busy} className={primaryClass}><Check className="size-4" />{busy ? "Đang lưu…" : "Lưu thay đổi"}</button></div></footer>
    </form>
  </AdminDialog>;
}

export function CourseLmsManager({ lmsSnapshot, studioMode = false }: { lmsSnapshot: AdminLmsSnapshot; studioMode?: boolean }) {
  const router = useRouter();
  const searchParams = useSearchParams();
  const [tab, setTab] = useState<Tab>(() => normalizedTab(searchParams.get("step")));
  const [editor, setEditor] = useState<Editor>(null);
  const [busy, setBusy] = useState(false);
  const [refreshing, startRefresh] = useTransition();
  const pending = useRef(false);
  const [error, setError] = useState("");
  const [message, setMessage] = useState("");
  const [confirm, setConfirm] = useState<{ title: string; description: string; payload: ActionPayload } | null>(null);
  const course = lmsSnapshot.selectedCourse;
  const locked = busy || refreshing;

  const submit: SubmitAction = async (payload) => {
    if (pending.current || refreshing) return false;
    pending.current = true; setBusy(true); setError(""); setMessage("");
    try {
      const response = await fetch("/api/admin/crm-v2/lms/actions", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(payload) });
      const result = await response.json().catch(() => null);
      if (!response.ok || !result?.ok) throw new Error(result?.message || "Không lưu được thay đổi. Nội dung đã nhập vẫn còn để anh thử lại.");
      setMessage(result.message || "Đã lưu thay đổi.");
      startRefresh(() => router.refresh());
      return true;
    } catch (cause) { setError(cause instanceof Error ? cause.message : "Kết nối gián đoạn. Anh có thể thử lưu lại."); return false; }
    finally { pending.current = false; setBusy(false); }
  };
  const openEditor = (next: Editor) => { if (locked) return; setError(""); setMessage(""); setEditor(next); };
  const archive = (title: string, payload: ActionPayload, resource = false) => { setError(""); setConfirm({ title, description: resource ? "Gỡ liên kết tài liệu này khỏi khóa học. Tệp gốc trong kho lưu trữ không bị xóa." : "Nội dung sẽ ngừng hiển thị với học viên. Bài học, tài liệu và tiến độ đã ghi nhận được giữ lại; anh có thể xuất bản lại sau.", payload }); };
  const changeTab = (next: Tab) => { setTab(next); const query = new URLSearchParams(searchParams.toString()); query.set("step", next); window.history.replaceState(window.history.state, "", `${studioMode ? "/admin/course-studio" : "/admin/crm-v2/courses"}/${encodeURIComponent(course?.slug || "")}?${query}`); };
  if (!lmsSnapshot.ok || !course) return <div data-admin-ui="modern" className="space-y-4"><Link href="/admin/crm-v2/courses" className={secondaryClass}><ArrowLeft className="size-4" />Khóa học</Link><div role="alert" className="rounded-xl border border-red-200 bg-red-50 p-5"><h1 className="font-semibold">{lmsSnapshot.ok ? "Không tìm thấy khóa học" : "Chưa tải được nội dung khóa học"}</h1><p className="mt-2 text-sm">{lmsSnapshot.message || "Anh có thể tải lại hoặc quay về danh sách khóa học."}</p><button type="button" className={`${secondaryClass} mt-3`} onClick={() => router.refresh()}>Tải lại</button></div></div>;

  return <div data-admin-ui="modern" className="min-w-0 space-y-3 text-slate-900">
    <header className="flex flex-wrap items-center justify-between gap-3">
      <div className="flex min-w-0 flex-1 items-center gap-3"><Link href="/admin/crm-v2/courses" aria-label="Về danh sách khóa học" className={`${secondaryClass} shrink-0`}><ArrowLeft className="size-4" /></Link><div className="min-w-0"><p className="text-xs text-slate-500">Khóa học</p><h1 className="break-words text-xl font-bold leading-7">{course.title}</h1></div></div>
      <div className="flex items-center gap-2"><Badge status={course.status} /><Link className={secondaryClass} href={`/khoa-hoc/${encodeURIComponent(course.slug)}`} target="_blank" rel="noopener noreferrer">Xem trang khóa học</Link></div>
    </header>
    {!editor && !confirm ? <><Notice message={error} error /><Notice message={message} /></> : null}
    <section className="min-w-0 overflow-hidden rounded-xl border border-slate-200 bg-white shadow-sm">
      <div className="flex items-center justify-between gap-2 border-b border-slate-200 px-3"><nav aria-label="Các phần của khóa học" className="flex min-w-0 gap-1 overflow-x-auto">{tabs.map(({ id, label, icon: Icon }) => <button key={id} type="button" aria-current={tab === id ? "page" : undefined} onClick={() => changeTab(id)} className={`inline-flex shrink-0 items-center gap-2 border-b-2 px-3 py-3.5 text-sm font-medium ${tab === id ? "border-blue-600 text-blue-600" : "border-transparent text-slate-500 hover:text-slate-900"}`}><Icon className="size-4" />{label}</button>)}</nav><span role="status" className="hidden shrink-0 text-xs text-slate-500 xl:block">{locked ? "Đang cập nhật…" : `${course.stats.publishedLessons}/${course.stats.lessons} bài đã xuất bản`}</span></div>
      <div className="min-w-0 lg:h-[calc(100dvh-230px)] lg:min-h-[440px] lg:overflow-auto">
        {tab === "curriculum" ? <Curriculum course={course} busy={locked} onEdit={openEditor} submit={submit} archive={archive} /> : null}
        {tab === "resources" ? <ResourceList course={course} busy={locked} onEdit={openEditor} archive={archive} /> : null}
        {tab === "students" ? <CourseStudents course={course} /> : null}
        <div hidden={tab !== "settings"}><CourseSettings key={`${course.id}:${course.updatedAt}`} course={course} busy={locked} error={error} submit={submit} archive={archive} /></div>
      </div>
    </section>
    {editor ? <EditorDialog title={editor.kind === "module" ? editor.module ? "Sửa chương học" : "Thêm chương học" : editor.kind === "lesson" ? editor.lesson ? "Sửa bài học" : "Thêm bài học" : editor.resource ? "Sửa tài liệu" : "Thêm tài liệu"} onClose={() => setEditor(null)} busy={locked} error={error} onSubmit={(data) => {
      const payload: ActionPayload = editor.kind === "module" ? { action: editor.module ? "update_module" : "create_module", courseId: course.id, moduleId: editor.module?.id, title: get(data, "title"), description: get(data, "description"), status: get(data, "status") } : editor.kind === "lesson" ? { action: editor.lesson ? "update_lesson" : "create_lesson", courseId: course.id, lessonId: editor.lesson?.id, moduleId: get(data, "moduleId"), title: get(data, "title"), slug: get(data, "slug") || undefined, description: get(data, "description"), content: get(data, "content"), lessonType: get(data, "lessonType"), duration: get(data, "duration"), youtubeUrl: get(data, "youtubeUrl"), embedUrl: editor.lesson && get(data, "youtubeUrl") !== editor.lesson.youtubeUrl && get(data, "embedUrl") === editor.lesson.embedUrl && editor.lesson.embedUrl === toYouTubeEmbedUrl(editor.lesson.youtubeUrl) ? "" : get(data, "embedUrl"), accessType: get(data, "accessType"), status: get(data, "status") } : (() => { const lessonId = get(data, "lessonId"); const parent = course.modules.find((module) => module.lessons.some((lesson) => lesson.id === lessonId)); return { action: editor.resource ? "update_resource" : "create_resource", courseId: course.id, resourceId: editor.resource?.id, moduleId: parent?.id ?? null, lessonId: lessonId || null, title: get(data, "title"), type: get(data, "type"), url: get(data, "url"), description: get(data, "description") }; })();
      void submit(payload).then((ok) => { if (ok) setEditor(null); });
    }}>
      {editor.kind === "module" ? <ModuleFields module={editor.module} /> : editor.kind === "lesson" ? <LessonFields course={course} lesson={editor.lesson} moduleId={editor.moduleId} /> : <ResourceFields course={course} resource={editor.resource} />}
    </EditorDialog> : null}
    <AdminDialog open={Boolean(confirm)} onClose={() => { if (!locked) setConfirm(null); }} title={confirm?.title || "Xác nhận"}><p className="text-sm leading-6 text-slate-600">{confirm?.description}</p><div className="mt-3"><Notice message={error} error /></div><div className="mt-5 flex justify-end gap-2"><button type="button" className={secondaryClass} disabled={locked} onClick={() => setConfirm(null)}>Hủy</button><button type="button" className="rounded-lg bg-red-600 px-4 py-2 text-sm font-semibold text-white disabled:opacity-50" disabled={locked} onClick={() => { if (confirm) void submit(confirm.payload).then((ok) => { if (ok) setConfirm(null); }); }}>{locked ? "Đang xử lý…" : "Xác nhận"}</button></div></AdminDialog>
  </div>;
}

type ArchiveAction = (title: string, payload: ActionPayload, resource?: boolean) => void;
function Curriculum({ course, busy, onEdit, submit, archive }: { course: LmsCourse; busy: boolean; onEdit: (editor: Editor) => void; submit: SubmitAction; archive: ArchiveAction }) {
  const [moduleId, setModuleId] = useState(course.modules.find((item) => item.status !== "archived")?.id || course.modules[0]?.id || "");
  const [search, setSearch] = useState("");
  const [showArchived, setShowArchived] = useState(false);
  const visibleModules = course.modules.filter((item) => showArchived || item.status !== "archived");
  const selected = visibleModules.find((item) => item.id === moduleId) || visibleModules[0];
  const lessons = (selected?.lessons || []).filter((lesson) => (showArchived || lesson.status !== "archived") && lesson.title.toLocaleLowerCase("vi").includes(search.trim().toLocaleLowerCase("vi")));
  const move = (kind: "module" | "lesson", id: string, direction: number) => {
    const items = kind === "module" ? course.modules : selected?.lessons || [];
    const ids = items.map((item) => item.id); const from = ids.indexOf(id); const to = from + direction;
    if (busy || from < 0 || to < 0 || to >= ids.length) return;
    [ids[from], ids[to]] = [ids[to], ids[from]];
    void submit(kind === "module" ? { action: "reorder_modules", courseId: course.id, moduleIds: ids } : { action: "reorder_lessons", moduleId: selected?.id, lessonIds: ids });
  };
  return <div className="grid min-h-full min-w-0 md:grid-cols-[260px_minmax(0,1fr)] xl:grid-cols-[280px_minmax(0,1fr)]">
    <aside className="min-w-0 border-b border-slate-200 bg-slate-50/70 md:border-b-0 md:border-r">
      <div className="flex items-center justify-between gap-2 border-b border-slate-200 p-3"><h2 className="text-sm font-semibold">Chương học <span className="font-normal text-slate-400">{visibleModules.length}</span></h2><button type="button" aria-label="Thêm chương học" disabled={busy} onClick={() => onEdit({ kind: "module" })} className="rounded-lg p-2 text-blue-600 hover:bg-blue-50 disabled:opacity-40"><Plus className="size-4" /></button></div>
      <div className="max-h-64 space-y-1 overflow-auto p-2 md:max-h-none">{visibleModules.map((module, index) => <div key={module.id} className={`rounded-lg border ${selected?.id === module.id ? "border-blue-200 bg-white shadow-sm" : "border-transparent"}`}>
        <button type="button" onClick={() => { setModuleId(module.id); setSearch(""); }} aria-pressed={selected?.id === module.id} className="flex w-full items-start gap-2 p-3 text-left"><span className="mt-0.5 text-xs tabular-nums text-slate-400">{String(index + 1).padStart(2, "0")}</span><span className="min-w-0 flex-1"><span className={`block break-words text-sm font-semibold leading-5 ${selected?.id === module.id ? "text-blue-700" : "text-slate-700"}`}>{module.title}</span><span className="mt-1 block text-xs text-slate-500">{module.lessons.filter((lesson) => lesson.status !== "archived").length} bài · {statusLabel(module.status)}</span></span><ChevronRight className="mt-1 size-3 shrink-0 text-slate-400" /></button>
        {selected?.id === module.id ? <div className="flex justify-end gap-1 border-t border-slate-100 px-2 py-1">{[-1, 1].map((direction) => <button key={direction} type="button" aria-label={`${direction < 0 ? "Đưa chương lên" : "Đưa chương xuống"}: ${module.title}`} disabled={busy || (direction < 0 ? course.modules[0]?.id === module.id : course.modules.at(-1)?.id === module.id)} onClick={() => move("module", module.id, direction)} className="rounded-md p-1.5 text-slate-500 hover:bg-slate-100 disabled:opacity-25">{direction < 0 ? <ArrowUp className="size-3.5" /> : <ArrowDown className="size-3.5" />}</button>)}<button type="button" aria-label={`Sửa chương: ${module.title}`} disabled={busy} onClick={() => onEdit({ kind: "module", module })} className="rounded-md p-1.5 text-slate-500 hover:bg-slate-100"><Pencil className="size-3.5" /></button></div> : null}
      </div>)}</div>
      {!visibleModules.length ? <div className="px-4 py-6 text-sm text-slate-500">Thêm chương để bắt đầu soạn bài học.</div> : null}
      <label className="flex items-center gap-2 border-t border-slate-200 px-3 py-3 text-xs text-slate-500"><input type="checkbox" checked={showArchived} onChange={(event) => setShowArchived(event.target.checked)} />Hiện nội dung đã lưu trữ</label>
    </aside>
    <div className="min-w-0">
      {selected ? <><div className="flex flex-wrap items-start justify-between gap-3 border-b border-slate-200 p-4"><div className="min-w-0"><h2 className="break-words text-base font-semibold">{selected.title}</h2><p className="mt-1 text-xs text-slate-500">{selected.lessons.filter((lesson) => lesson.status === "published").length} bài đã xuất bản · {selected.lessons.length} bài tổng cộng</p></div><button type="button" disabled={busy || selected.status === "archived"} onClick={() => onEdit({ kind: "lesson", moduleId: selected.id })} className={primaryClass}><Plus className="size-4" />Thêm bài học</button></div>
      <div className="flex flex-wrap items-center justify-between gap-2 border-b border-slate-100 p-3"><label className="relative w-full max-w-xs"><Search className="absolute left-3 top-3 size-4 text-slate-400" /><input className={`${inputClass} pl-9`} aria-label="Tìm bài học" value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Tìm trong chương này…" /></label><div className="flex gap-2"><button type="button" disabled={busy} onClick={() => onEdit({ kind: "module", module: selected })} className="px-2 py-2 text-xs font-medium text-slate-500 hover:text-blue-600">Sửa chương</button>{selected.status !== "archived" ? <button type="button" disabled={busy} onClick={() => archive("Lưu trữ chương học?", { action: "delete_module", moduleId: selected.id })} className="px-2 py-2 text-xs font-medium text-slate-500 hover:text-red-600">Lưu trữ</button> : null}</div></div>
      <div>{lessons.map((lesson) => <article key={lesson.id} className="flex flex-wrap items-center gap-3 border-b border-slate-100 p-4 hover:bg-slate-50/60"><button type="button" disabled={busy} onClick={() => onEdit({ kind: "lesson", lesson, moduleId: selected.id })} className="flex min-w-0 flex-1 items-center gap-3 text-left"><span className="grid size-9 shrink-0 place-items-center rounded-lg bg-slate-100 text-slate-500">{lesson.lessonType === "video" ? <Video className="size-4" /> : <FileText className="size-4" />}</span><span className="min-w-0"><span className="block break-words text-sm font-medium leading-5 hover:text-blue-600">{lesson.title}</span><span className="mt-1 block text-xs text-slate-500">{lesson.duration || "Chưa có thời lượng"} · {lesson.accessType === "free_preview" ? "Xem thử" : lesson.accessType === "locked" ? "Đang khóa" : "Dành cho học viên"}{lesson.resources.length ? ` · ${lesson.resources.length} tài liệu` : ""}</span></span></button><Badge status={lesson.status} /><div className="flex items-center gap-1">{[-1, 1].map((direction) => <button key={direction} type="button" aria-label={`${direction < 0 ? "Đưa bài lên" : "Đưa bài xuống"}: ${lesson.title}`} disabled={busy || (direction < 0 ? selected.lessons[0]?.id === lesson.id : selected.lessons.at(-1)?.id === lesson.id)} onClick={() => move("lesson", lesson.id, direction)} className="rounded-md p-2 text-slate-400 hover:bg-slate-100 disabled:opacity-25">{direction < 0 ? <ArrowUp className="size-3.5" /> : <ArrowDown className="size-3.5" />}</button>)}<button type="button" aria-label={`Sửa bài: ${lesson.title}`} disabled={busy} onClick={() => onEdit({ kind: "lesson", lesson, moduleId: selected.id })} className="rounded-md p-2 text-blue-600 hover:bg-blue-50"><Pencil className="size-4" /></button>{lesson.status !== "archived" ? <button type="button" aria-label={`Lưu trữ bài: ${lesson.title}`} disabled={busy} onClick={() => archive("Lưu trữ bài học?", { action: "delete_lesson", lessonId: lesson.id })} className="rounded-md p-2 text-slate-400 hover:bg-red-50 hover:text-red-600"><Archive className="size-4" /></button> : null}</div></article>)}</div>
      {!lessons.length ? <Empty>{search ? "Không có bài học khớp tìm kiếm." : "Chương này chưa có bài học. Bấm Thêm bài học để soạn nội dung."}</Empty> : null}</> : <Empty><div><BookOpen className="mx-auto mb-3 size-8 text-slate-300" /><p>Nội dung khóa học bắt đầu từ một chương.</p><button type="button" disabled={busy} onClick={() => onEdit({ kind: "module" })} className={`${primaryClass} mt-4`}><Plus className="size-4" />Thêm chương đầu tiên</button></div></Empty>}
    </div>
  </div>;
}

function ModuleFields({ module }: { module?: LmsModule }) { return <><Field label="Tên chương học"><input name="title" className={inputClass} defaultValue={module?.title || ""} maxLength={220} required autoFocus /></Field><Field label="Mô tả"><textarea name="description" rows={4} className={inputClass} defaultValue={module?.description || ""} maxLength={2000} /></Field><Field label="Trạng thái"><StatusSelect status={module?.status || "published"} /></Field></>; }
function LessonFields({ course, lesson, moduleId }: { course: LmsCourse; lesson?: LmsLesson; moduleId: string }) {
  const [section, setSection] = useState("content");
  const [type, setType] = useState(lesson?.lessonType || "video");
  return <><Field label="Tên bài học"><input name="title" className={inputClass} defaultValue={lesson?.title || ""} maxLength={220} required autoFocus /></Field><div className="flex gap-1 rounded-lg bg-slate-100 p-1" role="group" aria-label="Chi tiết bài học">{[["content", "Nội dung"], ["settings", "Thiết lập & quyền xem"]].map(([key, label]) => <button key={key} type="button" aria-pressed={section === key} className={`flex-1 rounded-md px-3 py-2 text-sm font-medium ${section === key ? "bg-white text-blue-700 shadow-sm" : "text-slate-500"}`} onClick={() => setSection(key)}>{label}</button>)}</div>
    <div hidden={section !== "content"} className="space-y-4"><div className="grid gap-4 sm:grid-cols-2"><Field label="Loại bài học"><select className={inputClass} name="lessonType" value={type} onChange={(event) => setType(event.target.value as typeof type)}>{[["video", "Video"], ["text", "Bài viết"], ["file", "Tệp tài liệu"], ["link", "Liên kết"], ["live", "Buổi học trực tuyến"]].map(([key, label]) => <option key={key} value={key}>{label}</option>)}</select></Field><Field label="Thời lượng"><input className={inputClass} name="duration" defaultValue={lesson?.duration || ""} maxLength={160} placeholder="Ví dụ: 12 phút" /></Field></div>
      <div className="grid gap-4 sm:grid-cols-2"><Field label="Đường dẫn video / buổi học"><input className={inputClass} name="youtubeUrl" defaultValue={lesson?.youtubeUrl || ""} placeholder="https://…" maxLength={500} /></Field><Field label="Đường dẫn nhúng" hint="Có thể để trống với video YouTube."><input className={inputClass} name="embedUrl" defaultValue={lesson?.embedUrl || ""} placeholder="https://…" maxLength={500} /></Field></div>
      <Field label="Giới thiệu ngắn"><textarea className={inputClass} rows={2} name="description" defaultValue={lesson?.description || ""} maxLength={3000} /></Field><Field label="Nội dung bài học" hint="Nội dung văn bản/HTML được giữ theo định dạng phòng học hiện tại."><textarea className={`${inputClass} min-h-48 font-mono leading-6`} name="content" defaultValue={lesson?.content || ""} maxLength={40000} /></Field>
    </div>
    <div hidden={section !== "settings"} className="space-y-4"><Field label="Chương học"><select className={inputClass} name="moduleId" defaultValue={moduleId}>{course.modules.filter((module) => module.status !== "archived" || module.id === moduleId).map((module) => <option key={module.id} value={module.id}>{module.title}</option>)}</select></Field><Field label="Đường dẫn bài học" hint="Để trống khi tạo mới để lấy từ tên bài."><input className={inputClass} name="slug" defaultValue={lesson?.slug || ""} /></Field><div className="grid gap-4 sm:grid-cols-2"><Field label="Trạng thái"><StatusSelect status={lesson?.status} /></Field><Field label="Quyền xem"><select className={inputClass} name="accessType" defaultValue={lesson?.accessType || "enrolled_only"}><option value="enrolled_only">Học viên được cấp quyền</option><option value="free_preview">Cho phép xem thử</option><option value="locked">Tạm khóa bài học</option></select></Field></div></div>
  </>;
}

function ResourceList({ course, busy, onEdit, archive }: { course: LmsCourse; busy: boolean; onEdit: (editor: Editor) => void; archive: ArchiveAction }) {
  const [search, setSearch] = useState("");
  const [scope, setScope] = useState("all");
  const available = allResources(course);
  const resources = available.filter((resource) => resource.title.toLocaleLowerCase("vi").includes(search.toLocaleLowerCase("vi")) && (scope === "all" || (scope === "course" ? !resource.lessonId : Boolean(resource.lessonId))));
  return <div className="min-w-0"><div className="flex flex-wrap items-center justify-between gap-3 border-b border-slate-200 p-4"><div><h2 className="text-base font-semibold">Tài liệu khóa học</h2><p className="mt-1 text-xs text-slate-500">{available.length} tài liệu · dùng cho toàn khóa hoặc một bài học</p></div><button type="button" disabled={busy} onClick={() => onEdit({ kind: "resource" })} className={primaryClass}><Plus className="size-4" />Thêm tài liệu</button></div><div className="flex flex-wrap gap-3 border-b border-slate-100 p-3"><input aria-label="Tìm tài liệu" value={search} onChange={(event) => setSearch(event.target.value)} className={`${inputClass} max-w-xs`} placeholder="Tìm tài liệu…" /><select aria-label="Phạm vi tài liệu" value={scope} onChange={(event) => setScope(event.target.value)} className={`${inputClass} max-w-48`}><option value="all">Tất cả tài liệu</option><option value="course">Dùng cho toàn khóa</option><option value="lesson">Theo bài học</option></select></div>{resources.map((resource) => { const lesson = course.modules.flatMap((module) => module.lessons).find((item) => item.id === resource.lessonId); return <article key={resource.id} className="flex items-center gap-3 border-b border-slate-100 p-4"><FileText className="size-5 shrink-0 text-slate-400" /><button type="button" disabled={busy} onClick={() => onEdit({ kind: "resource", resource })} className="min-w-0 flex-1 text-left"><span className="block break-words text-sm font-medium text-slate-800 hover:text-blue-600">{resource.title}</span><span className="mt-1 block break-words text-xs text-slate-500">{lesson?.title || "Toàn khóa"} · {resource.type}</span></button><button type="button" aria-label={`Sửa tài liệu: ${resource.title}`} disabled={busy} onClick={() => onEdit({ kind: "resource", resource })} className="rounded-lg p-2 text-blue-600 hover:bg-blue-50"><Pencil className="size-4" /></button><button type="button" aria-label={`Gỡ tài liệu: ${resource.title}`} disabled={busy} onClick={() => archive("Gỡ tài liệu khỏi khóa học?", { action: "delete_resource", resourceId: resource.id }, true)} className="rounded-lg p-2 text-slate-400 hover:bg-red-50 hover:text-red-600"><Trash2 className="size-4" /></button></article>; })}{!resources.length ? <Empty>Chưa có tài liệu phù hợp.</Empty> : null}</div>;
}
function ResourceFields({ course, resource }: { course: LmsCourse; resource?: LmsResource }) { return <><Field label="Tên tài liệu"><input name="title" required maxLength={220} defaultValue={resource?.title || ""} className={inputClass} autoFocus /></Field><div className="grid gap-4 sm:grid-cols-2"><Field label="Phạm vi sử dụng"><select name="lessonId" defaultValue={resource?.lessonId || ""} className={inputClass}><option value="">Toàn khóa học</option>{course.modules.map((module) => <optgroup key={module.id} label={module.title}>{module.lessons.map((lesson) => <option key={lesson.id} value={lesson.id}>{lesson.title}</option>)}</optgroup>)}</select></Field><Field label="Loại tài liệu"><select name="type" defaultValue={resource?.type || "link"} className={inputClass}>{[["link", "Liên kết"], ["file", "Tệp tài liệu"], ["worksheet", "Bài tập"], ["template", "Biểu mẫu"], ["video", "Video"], ["other", "Khác"]].map(([key, label]) => <option key={key} value={key}>{label}</option>)}</select></Field></div><Field label="Đường dẫn tài liệu" hint="Dùng liên kết HTTPS hoặc đường dẫn tệp bắt đầu bằng /."><input name="url" required maxLength={1000} defaultValue={resource?.url || ""} className={inputClass} placeholder="https://…" /></Field><Field label="Mô tả"><textarea name="description" rows={3} maxLength={2000} defaultValue={resource?.description || ""} className={inputClass} /></Field></>; }

function CourseStudents({ course }: { course: LmsCourse }) {
  const [search, setSearch] = useState("");
  const [status, setStatus] = useState("all");
  const rows = course.enrollments.filter((item) => (status === "all" || item.status === status) && `${item.studentName} ${item.email} ${item.phone}`.toLocaleLowerCase("vi").includes(search.toLocaleLowerCase("vi")));
  const current = course.enrollments.filter((item) => item.status === "active" || item.status === "completed");
  const average = current.length ? Math.round(current.reduce((sum, item) => sum + Math.max(0, Math.min(100, item.progressPercent)), 0) / current.length) : 0;
  return <div><div className="flex flex-wrap items-center justify-between gap-3 border-b border-slate-200 p-4"><div><h2 className="text-base font-semibold">Học viên của khóa</h2><p className="mt-1 text-xs text-slate-500">{course.enrollments.length} lượt ghi danh · tiến độ trung bình {average}% của học viên đang học/hoàn thành</p></div><Link href={`/admin/crm-v2/customers?course=${encodeURIComponent(course.slug)}`} className={primaryClass}><Users className="size-4" />Quản lý hồ sơ & quyền học</Link></div><div className="flex flex-wrap gap-3 border-b border-slate-100 p-3"><input aria-label="Tìm học viên trong khóa" value={search} onChange={(event) => setSearch(event.target.value)} className={`${inputClass} max-w-xs`} placeholder="Tên, email, số điện thoại…" /><select aria-label="Lọc quyền học" value={status} onChange={(event) => setStatus(event.target.value)} className={`${inputClass} max-w-48`}><option value="all">Tất cả trạng thái</option>{["active", "completed", "paused", "revoked"].map((key) => <option key={key} value={key}>{statusLabel(key)}</option>)}</select></div>{rows.map((enrollment) => <Link key={enrollment.id} href={`/admin/crm-v2/customers?q=${encodeURIComponent(enrollment.email || enrollment.phone)}&course=${encodeURIComponent(course.slug)}&profile=${encodeURIComponent(enrollment.email || enrollment.phone)}`} className="flex flex-wrap items-center gap-4 border-b border-slate-100 p-4 hover:bg-blue-50/40"><div className="min-w-0 flex-1"><p className="break-words text-sm font-medium">{enrollment.studentName || enrollment.email || "Chưa có tên"}</p><p className="mt-1 break-words text-xs text-slate-500">{enrollment.email || enrollment.phone}</p></div><Badge status={enrollment.status} /><div className="w-28"><div className="mb-1 flex justify-between text-xs text-slate-500"><span>Tiến độ</span><span>{enrollment.progressPercent}%</span></div><div className="h-1.5 overflow-hidden rounded-full bg-slate-100"><div className="h-full rounded-full bg-blue-600" style={{ width: `${Math.max(0, Math.min(100, enrollment.progressPercent))}%` }} /></div></div><ChevronRight className="size-4 text-slate-400" /></Link>)}{!rows.length ? <Empty>Chưa có học viên phù hợp.</Empty> : null}</div>;
}

function CourseSettings({ course, busy, error, submit, archive }: { course: LmsCourse; busy: boolean; error: string; submit: SubmitAction; archive: ArchiveAction }) {
  const [section, setSection] = useState("general");
  const [dirty, setDirty] = useState(false);
  const [uploads, setUploads] = useState(0);
  const setUploading = (active: boolean) => setUploads((count) => Math.max(0, count + (active ? 1 : -1)));
  useEffect(() => { if (!dirty) return; const beforeUnload = (event: BeforeUnloadEvent) => { event.preventDefault(); }; window.addEventListener("beforeunload", beforeUnload); return () => window.removeEventListener("beforeunload", beforeUnload); }, [dirty]);
  return <form className="mx-auto max-w-5xl p-4 md:p-5" onInvalidCapture={(event) => { const target = event.target as HTMLInputElement; if (["price", "originalPrice", "duration", "level", "ctaText"].includes(target.name)) setSection("pricing"); else if (["thumbnailImage", "bannerImage", "previewVideoUrl"].includes(target.name)) setSection("media"); else setSection("general"); }} onChange={() => setDirty(true)} onSubmit={(event) => { event.preventDefault(); const data = new FormData(event.currentTarget); void submit({ action: "update_course", courseId: course.id, title: get(data, "title"), slug: course.slug, shortDescription: get(data, "shortDescription"), description: get(data, "description"), price: Number(get(data, "price")), originalPrice: Number(get(data, "originalPrice")), duration: get(data, "duration"), level: get(data, "level"), ctaText: get(data, "ctaText"), thumbnailImage: get(data, "thumbnailImage"), bannerImage: get(data, "bannerImage"), previewVideoUrl: get(data, "previewVideoUrl"), status: get(data, "status"), visibility: get(data, "visibility") }).then((ok) => { if (ok) setDirty(false); }); }}>
    <div className="mb-5 flex flex-wrap items-center justify-between gap-3"><div><h2 className="text-base font-semibold">Thông tin & xuất bản</h2><p className="mt-1 text-xs text-slate-500">{dirty ? "Có thay đổi chưa lưu" : "Cập nhật nội dung hiển thị của khóa học"}</p></div><button type="submit" disabled={busy || uploads > 0} className={primaryClass}><Check className="size-4" />{busy ? "Đang lưu…" : "Lưu thay đổi"}</button></div>
    <div role="group" aria-label="Thông tin khóa học" className="mb-5 flex gap-1 overflow-x-auto rounded-lg bg-slate-100 p-1">{[["general", "Thông tin chung"], ["pricing", "Giá & giới thiệu"], ["media", "Ảnh & video"], ["publishing", "Xuất bản"]].map(([id, label]) => <button key={id} type="button" aria-pressed={section === id} onClick={() => setSection(id)} className={`shrink-0 rounded-md px-3 py-2 text-sm font-medium ${section === id ? "bg-white text-blue-700 shadow-sm" : "text-slate-500"}`}>{label}</button>)}</div>
    <fieldset disabled={busy} className="space-y-4">
      <div hidden={section !== "general"} className="space-y-4"><Field label="Tên khóa học"><input name="title" required maxLength={220} className={inputClass} defaultValue={course.title} /></Field><Field label="Đường dẫn khóa học" hint="Giữ cố định để các liên kết, đơn hàng và quyền học hiện có tiếp tục hoạt động."><input className={`${inputClass} bg-slate-50 text-slate-500`} value={course.slug} readOnly /></Field><Field label="Mô tả ngắn"><textarea name="shortDescription" className={inputClass} rows={3} maxLength={500} defaultValue={course.shortDescription} /></Field><Field label="Mô tả đầy đủ"><textarea name="description" className={inputClass} rows={6} maxLength={5000} defaultValue={course.description} /></Field></div>
      <div hidden={section !== "pricing"} className="grid gap-4 sm:grid-cols-2"><Field label="Giá bán (VND)"><input type="number" min={0} max={2147483647} step={1} name="price" className={inputClass} defaultValue={course.price ?? 0} /></Field><Field label="Giá gốc (VND)"><input type="number" min={0} max={2147483647} step={1} name="originalPrice" className={inputClass} defaultValue={course.originalPrice ?? 0} /></Field><Field label="Thời lượng"><input name="duration" maxLength={160} className={inputClass} defaultValue={course.duration || ""} /></Field><Field label="Trình độ"><input name="level" maxLength={160} className={inputClass} defaultValue={course.level || ""} /></Field><Field label="Nhãn nút đăng ký"><input name="ctaText" maxLength={160} className={inputClass} defaultValue={course.ctaText || ""} /></Field></div>
      <div hidden={section !== "media"} className="space-y-4"><div className="grid gap-4 md:grid-cols-2"><CourseImage course={course} name="thumbnailImage" label="Ảnh đại diện" onUploading={setUploading} onDirty={() => setDirty(true)} /><CourseImage course={course} name="bannerImage" label="Ảnh bìa" onUploading={setUploading} onDirty={() => setDirty(true)} /></div><Field label="Video giới thiệu"><input name="previewVideoUrl" className={inputClass} defaultValue={course.previewVideoUrl} maxLength={500} /></Field></div>
      <div hidden={section !== "publishing"} className="space-y-5"><div className="grid gap-4 sm:grid-cols-2"><Field label="Trạng thái khóa học"><StatusSelect status={course.status} /></Field><Field label="Phạm vi truy cập"><select name="visibility" className={inputClass} defaultValue={course.visibility}><option value="enrolled">Học viên được cấp quyền</option><option value="public">Công khai</option><option value="private">Riêng tư</option></select></Field></div><div className="rounded-lg border border-slate-200 p-4"><h3 className="text-sm font-semibold">Kiểm tra nội dung</h3><ul className="mt-3 space-y-2 text-sm text-slate-600">{[[Boolean(course.title), "Tên khóa học"], [Boolean(course.shortDescription || course.description), "Mô tả khóa học"], [Boolean(course.thumbnailImage || course.bannerImage), "Ảnh đại diện"], [course.modules.some((module) => module.status === "published" && module.lessons.some((lesson) => lesson.status === "published")), "Có bài học được xuất bản trong chương đang hiển thị"]].map(([ready, label]) => <li key={String(label)} className="flex items-center justify-between gap-3"><span>{String(label)}</span><span className={`text-xs font-medium ${ready ? "text-emerald-600" : "text-amber-600"}`}>{ready ? "Đã có" : "Chưa có"}</span></li>)}</ul></div>{course.status !== "archived" ? <div className="flex flex-wrap items-center justify-between gap-3 rounded-lg border border-slate-200 p-4"><div><h3 className="text-sm font-semibold">Lưu trữ khóa học</h3><p className="mt-1 text-xs text-slate-500">Ngừng hiển thị; giữ nội dung và lịch sử học viên.</p></div><button type="button" disabled={busy} onClick={() => archive("Lưu trữ khóa học?", { action: "archive_course", courseId: course.id })} className={secondaryClass}><Archive className="size-4" />Lưu trữ</button></div> : <p className="text-sm text-slate-500">Khóa đã lưu trữ. Chọn Đang xuất bản và lưu để mở lại.</p>}</div>
    </fieldset>
    <div className="mt-4"><Notice message={error} error /></div>
  </form>;
}
function CourseImage({ course, name, label, onUploading, onDirty }: { course: LmsCourse; name: "thumbnailImage" | "bannerImage"; label: string; onUploading: (value: boolean) => void; onDirty: () => void }) {
  const [url, setUrl] = useState(course[name]);
  const [busy, setBusy] = useState(false);
  const [error, setError] = useState("");
  async function upload(file: File | undefined) { if (!file || busy) return; const client = createSupabaseBrowserClient(); if (!client) { setError("Chưa kết nối được kho ảnh."); return; } setBusy(true); onUploading(true); setError(""); try { const next = await uploadMediaFile({ file, folder: `courses/${course.slug}/${name}`, supabase: client }); setUrl(next); onDirty(); } catch (cause) { setError(cause instanceof Error ? cause.message : "Không tải được ảnh."); } finally { setBusy(false); onUploading(false); } }
  return <div className="space-y-3 rounded-lg border border-slate-200 p-3"><p className="text-sm font-medium">{label}</p><div className="grid aspect-[3/1] place-items-center overflow-hidden rounded-lg bg-slate-50">{url ? <Image alt={label} src={url} width={600} height={200} unoptimized className="size-full object-contain" /> : <span className="text-xs text-slate-400">Chưa có ảnh</span>}</div><label className="flex cursor-pointer items-center justify-center gap-2 rounded-lg border border-slate-200 p-2 text-xs font-medium"><Upload className="size-3.5" />{busy ? "Đang tải ảnh…" : "Tải ảnh lên"}<input disabled={busy} accept="image/*" type="file" className="sr-only" onChange={(event) => { void upload(event.target.files?.[0]); event.currentTarget.value = ""; }} /></label><input aria-label={`Đường dẫn ${label.toLowerCase()}`} name={name} className={inputClass} value={url} onChange={(event) => { setUrl(event.target.value); onDirty(); }} maxLength={500} placeholder="https://…" /><Notice message={error} error /></div>;
}
