"use client";
import { useDeferredValue, useEffect, useMemo, useRef, useState, type ReactNode } from "react";
import { useRouter } from "next/navigation";
import { Search, Users, ChevronLeft, ChevronRight, ArrowUpRight, ShieldBan, ShieldCheck } from "lucide-react";
import { AdminDialog } from "@/components/admin/admin-dialog";
import { StudentActivityTimeline } from "@/components/admin/student-activity-timeline";
import type { Course } from "@/data/courses";
import type { StudentAccessRecord } from "@/services/studentAccessService";

const inputClass = "h-10 min-w-0 rounded-lg border border-slate-200 bg-white px-3 text-sm text-slate-800 outline-none focus:border-blue-500 focus:ring-2 focus:ring-blue-100";
const buttonClass = "rounded-lg border border-slate-200 bg-white px-3 py-2 text-sm font-semibold text-slate-700 hover:bg-slate-50 disabled:opacity-40";
function date(value: string) { const d = new Date(value); return Number.isNaN(d.getTime()) ? "—" : d.toLocaleDateString("vi-VN", { timeZone: "Asia/Ho_Chi_Minh" }); }
function searchable(row: StudentAccessRecord) { return [row.name, row.email, row.phone, ...row.courseTitles, ...row.paidOrderCodes, ...row.pendingOrderCodes].join(" ").normalize("NFD").replace(/[\u0300-\u036f]/g, "").replace(/[đĐ]/g, "d").toLowerCase(); }
export function CustomerDirectory({ records, courses, canManageAccount, initialSearch = "", initialCourse = "", initialProfile = "", createAction }: {
  records: StudentAccessRecord[]; courses: Pick<Course, "slug" | "title">[]; canManageAccount: boolean; initialSearch?: string; initialCourse?: string; initialProfile?: string; createAction: ReactNode;
}) {
  const [search, setSearch] = useState(initialSearch);
  const deferredSearch = useDeferredValue(search);
  const scrollRef = useRef<HTMLDivElement>(null);
  const searchIndex = useMemo(() => new Map(records.map((row) => [row.id, searchable(row)])), [records]);
  const [course, setCourse] = useState(initialCourse);
  const [segment, setSegment] = useState("all");
  const [page, setPage] = useState(1);
  const [profileBusy, setProfileBusy] = useState(false);
  const [profileId, setProfileId] = useState(() => records.find((row) => initialProfile && (row.email === initialProfile || row.id === initialProfile))?.id ?? "");
  const filtered = useMemo(() => { const term = deferredSearch.normalize("NFD").replace(/[\u0300-\u036f]/g, "").replace(/[đĐ]/g, "d").toLowerCase().trim(); return records.filter((row) => (!term || searchIndex.get(row.id)?.includes(term)) && (!course || row.courseSlugs.includes(course)) && (segment === "all" || (segment === "students" ? Boolean(row.accessibleCourseSlugs?.length) : segment === "paid" ? row.paidOrderCodes.length > 0 : !row.accessibleCourseSlugs?.length))); }, [records, deferredSearch, course, segment, searchIndex]);
  const count = Math.max(1, Math.ceil(filtered.length / 25));
  const current = Math.min(page, count);
  const visible = filtered.slice((current - 1) * 25, current * 25);
  const selected = records.find((row) => row.id === profileId);
  const totals = useMemo(() => ({ all: records.length, students: records.filter((row) => row.accessibleCourseSlugs?.length).length, paid: records.filter((row) => row.paidOrderCodes.length).length }), [records]);
  useEffect(() => { if (scrollRef.current) scrollRef.current.scrollTop = 0; }, [deferredSearch, course, segment, current]);
  return <div data-admin-ui="modern" className="space-y-4">
    <header className="flex flex-wrap items-start justify-between gap-3"><div><h1 className="text-2xl font-bold tracking-tight">Khách hàng & học viên</h1><p className="mt-1 text-sm text-slate-500">Một hồ sơ cho liên hệ, đơn hàng, quyền học và hoạt động.</p></div>{createAction}</header>
    <div className="flex flex-wrap gap-2" aria-label="Lọc nhóm hồ sơ">{[["all", "Tất cả", totals.all], ["students", "Có quyền học", totals.students], ["paid", "Đã mua", totals.paid], ["leads", "Chưa có quyền", records.length - totals.students]].map(([key,label,total]) => <button key={key} type="button" aria-pressed={segment === key} onClick={() => { setSegment(String(key)); setPage(1); }} className={`rounded-lg border px-3 py-2 text-sm font-semibold ${segment === key ? "border-blue-200 bg-blue-50 text-blue-700" : "border-slate-200 bg-white text-slate-600"}`}>{label} <span className="ml-2 rounded bg-white/70 px-1.5 text-xs tabular-nums">{total}</span></button>)}</div>
    <section className="overflow-hidden rounded-xl border border-slate-200 bg-white">
      <div className="flex flex-wrap items-center gap-3 border-b border-slate-200 p-4"><label className="flex min-w-[200px] max-w-md flex-1 items-center gap-2"><Search className="size-4 text-slate-400" /><input aria-label="Tìm trong hồ sơ" value={search} onChange={(e) => { setSearch(e.target.value); setPage(1); }} placeholder="Tên, email, điện thoại, mã đơn…" className={`${inputClass} w-full`} type="search" /></label>
        <select aria-label="Lọc khóa học" className={`${inputClass} max-w-[320px]`} value={course} onChange={(e) => { setCourse(e.target.value); setPage(1); }}><option value="">Tất cả khóa học</option>{courses.map((item) => <option key={item.slug} value={item.slug}>{item.title}</option>)}</select>
        <span className="ml-auto text-sm text-slate-500">{filtered.length} hồ sơ</span>
      </div>
      <div ref={scrollRef} aria-busy={search !== deferredSearch} className="max-h-[calc(100dvh-330px)] min-h-56 overflow-auto"><table className="w-full min-w-[680px] table-fixed text-left text-sm"><thead className="sticky top-0 z-10 bg-slate-50 text-xs font-semibold text-slate-500"><tr><th className="w-[36%] px-4 py-3">Hồ sơ / liên hệ</th><th className="w-[30%] px-4 py-3">Khóa học</th><th className="w-[20%] px-4 py-3">Trạng thái</th><th className="px-4 py-3"><span className="sr-only">Mở hồ sơ</span></th></tr></thead><tbody>
        {visible.map((row) => <tr key={row.id} className="border-t border-slate-100 hover:bg-blue-50/40"><td className="px-4 py-3"><button type="button" onClick={() => setProfileId(row.id)} className="flex max-w-full items-center gap-3 text-left"><span className="grid size-9 shrink-0 place-items-center rounded-full bg-blue-50 font-bold text-blue-700">{(row.name || row.email || "?").slice(0,1).toUpperCase()}</span><span className="min-w-0"><span className="block truncate font-semibold text-slate-900">{row.name || "Chưa có tên"}</span><span className="block truncate text-xs text-slate-500">{row.email || row.phone || "Chưa có liên hệ"}</span>{row.email && row.phone ? <span className="block text-xs text-slate-400">{row.phone}</span> : null}</span></button></td>
          <td className="px-4 py-3"><span className="line-clamp-2 text-xs leading-5 text-slate-600" title={row.courseTitles.join(" · ")}>{row.courseTitles[0] || "Chưa đăng ký khóa học"}</span>{row.courseTitles.length > 1 ? <button type="button" onClick={() => setProfileId(row.id)} className="text-xs font-semibold text-blue-700">+{row.courseTitles.length - 1} khóa khác</button> : null}</td>
          <td className="px-4 py-3"><span className={`inline-flex rounded-md px-2 py-1 text-xs font-semibold ${row.accessibleCourseSlugs?.length ? "bg-emerald-50 text-emerald-700" : "bg-slate-100 text-slate-600"}`}>{row.accessibleCourseSlugs?.length ? "Có quyền học" : "Khách hàng"}</span><span className="mt-1 block text-xs text-slate-500">{row.paidOrderCodes.length ? `${row.paidOrderCodes.length} đơn đã mua` : "Chưa có đơn đã trả"}</span></td>
          <td className="px-4 py-3 text-right"><button aria-label={`Mở hồ sơ ${row.name || row.email || row.phone}`} className="rounded-lg p-2 text-blue-700 hover:bg-blue-100" type="button" onClick={() => setProfileId(row.id)}><ArrowUpRight className="size-4" /></button></td></tr>)}
      </tbody></table>{!visible.length ? <div className="p-12 text-center text-sm text-slate-500"><Users className="mx-auto mb-3 size-8 text-slate-300" />Không có hồ sơ khớp bộ lọc.<button type="button" className="mx-auto mt-3 block text-blue-700" onClick={() => { setSearch(""); setCourse(""); setSegment("all"); }}>Xóa bộ lọc</button></div> : null}</div>
      <footer className="flex items-center justify-between border-t border-slate-200 px-4 py-3 text-xs text-slate-500"><span>{filtered.length ? (current - 1) * 25 + 1 : 0}–{Math.min(current * 25, filtered.length)} / {filtered.length} hồ sơ</span><div className="flex items-center gap-3"><button type="button" aria-label="Trang trước" className={buttonClass} disabled={current === 1} onClick={() => setPage(current - 1)}><ChevronLeft className="size-4" /></button><span>{current}/{count}</span><button type="button" aria-label="Trang tiếp" className={buttonClass} disabled={current === count} onClick={() => setPage(current + 1)}><ChevronRight className="size-4" /></button></div></footer>
    </section>
    <AdminDialog open={Boolean(selected)} busy={profileBusy} onClose={() => { if (!profileBusy) setProfileId(""); }} title={selected?.name || selected?.email || "Hồ sơ khách hàng"} description="Hồ sơ khách hàng & học viên" wide>{selected ? <CustomerProfile key={selected.id} student={selected} courses={courses} canManageAccount={canManageAccount} onBusyChange={setProfileBusy} onDeleted={() => setProfileId("")} /> : null}</AdminDialog>
  </div>;
}

type AccountState = { exists: boolean; blocked: boolean; protected: boolean };
function CustomerProfile({ student, courses, canManageAccount, onDeleted, onBusyChange }: { student: StudentAccessRecord; courses: Pick<Course, "slug" | "title">[]; canManageAccount: boolean; onDeleted: () => void; onBusyChange: (busy: boolean) => void }) {
  const router = useRouter();
  const [tab, setTab] = useState("overview");
  const [selected, setSelected] = useState<string[]>(student.accessibleCourseSlugs ?? []);
  const [pending, setPending] = useState("");
  useEffect(() => { onBusyChange(Boolean(pending)); return () => onBusyChange(false); }, [pending, onBusyChange]);
  const [confirmation, setConfirmation] = useState("");
  const [message, setMessage] = useState("");
  const [account, setAccount] = useState<AccountState | null>(null);
  const [accountError, setAccountError] = useState("");
  const [reload, setReload] = useState(0);
  useEffect(() => {
    if (!student.email || tab !== "account") return;
    let active = true;
    const controller = new AbortController();
    fetch(`/api/admin/customers/account?email=${encodeURIComponent(student.email)}`, { signal: controller.signal, cache: "no-store" })
      .then(async (response) => { const data = await response.json(); if (!response.ok || !data.ok) throw new Error(data.message || "Không đọc được tài khoản."); if (active) { setAccount(data); setAccountError(""); } })
      .catch((error) => { if (active) setAccountError(error.message || "Mất kết nối."); });
    return () => { active = false; controller.abort(); };
  }, [student.email, reload, tab]);
  async function run(action: string) {
    const paths: Record<string, string> = { grant: "/api/admin/students/access", revoke: "/api/admin/students/access", password: "/api/admin/students/password-reset", delete: "/api/admin/students/delete", block: "/api/admin/customers/account", unblock: "/api/admin/customers/account" };
    setPending(action); setMessage("");
    try {
      const response = await fetch(paths[action], { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ email: student.email, phone: student.phone, name: student.name, action, courseSlugs: selected, ...(action === "block" || action === "unblock" ? { blocked: action === "block" } : {}) }) });
      const result = await response.json();
      if (!response.ok || !result.ok) { if (action === "block" || action === "unblock") { setAccount(null); setReload((x) => x + 1); setConfirmation(""); } setMessage(result.message || "Thao tác chưa thành công."); if (result.accessUpdated || result.accountUpdated) { router.refresh(); setReload((x) => x + 1); setConfirmation(""); } return; }
      setMessage(result.message || "Đã cập nhật."); setConfirmation(""); router.refresh();
      if (action === "delete") onDeleted();
      if (action === "block" || action === "unblock") { setAccount((current) => current ? { ...current, blocked: result.blocked } : null); setReload((x) => x + 1); }
    } catch { setMessage("Mất kết nối. Hãy tải lại hồ sơ để kiểm tra kết quả trước khi thao tác lại."); setConfirmation(""); setAccount(null); setReload((x) => x + 1); router.refresh(); }
    finally { setPending(""); }
  }
  const labels: Record<string,string> = { grant: "Cấp quyền các khóa đã chọn", revoke: "Thu hồi quyền các khóa đã chọn", password: "Cấp lại mật khẩu và gửi email", delete: "Xóa hồ sơ khỏi danh sách", block: "Chặn đăng nhập", unblock: "Mở lại đăng nhập" };
  const details: Record<string,string> = { grant: "Quyền học được cấp theo danh sách đã chọn; hệ thống gửi email hướng dẫn qua luồng hiện có.", revoke: "Học viên sẽ mất quyền vào các khóa đã chọn. Đơn hàng và tiến độ học được giữ.", password: "Mật khẩu hiện tại sẽ thay đổi và email đăng nhập mới sẽ được gửi cho khách.", delete: "Hồ sơ được ẩn và đưa vào lịch xóa sau 30 ngày theo quy trình hiện có. Đơn hàng đã thanh toán được giữ để đối soát.", block: "Ngăn đăng nhập và gia hạn phiên. Phiên hiện tại có thể còn hiệu lực đến khi hết hạn. Giữ nguyên quyền học, đơn hàng và tiến độ.", unblock: "Cho phép tài khoản đăng nhập lại, giữ nguyên quyền học hiện có." };
  return <div className="grid gap-5 md:grid-cols-[230px_minmax(0,1fr)]">
    <aside className="min-w-0 rounded-xl bg-slate-50 p-4"><span className="grid size-14 place-items-center rounded-full bg-blue-100 text-xl font-bold text-blue-700">{(student.name || student.email || "?").slice(0,1).toUpperCase()}</span><h3 className="mt-3 break-words font-semibold">{student.name || "Chưa có tên"}</h3><p className="mt-1 break-all text-sm text-slate-600">{student.email || "Chưa có email"}</p><p className="mt-1 text-sm text-slate-600">{student.phone || "Chưa có điện thoại"}</p><div className="mt-5 space-y-2 border-t border-slate-200 pt-4 text-xs text-slate-500"><p>Đăng ký: {date(student.registeredAt)}</p><p>{student.accessibleCourseSlugs?.length ?? 0} khóa có quyền học</p><p>{student.paidOrderCodes.length} đơn đã thanh toán</p></div>{student.phone ? <a className="mt-4 block text-sm font-semibold text-blue-700" href={`https://zalo.me/${student.phone.replace(/\D/g, "")}`} target="_blank" rel="noopener noreferrer">Mở Zalo ↗</a> : null}</aside>
    <div className="min-w-0"><nav aria-label="Thông tin hồ sơ" className="mb-4 flex gap-1 overflow-x-auto border-b border-slate-200 pb-3">{[["overview","Thông tin"],["access","Quyền học"],["orders","Đơn hàng"],["activity","Hoạt động"],["account","Tài khoản"]].map(([id,label]) => <button key={id} type="button" aria-pressed={tab === id} className={`whitespace-nowrap rounded-lg px-3 py-2 text-sm font-semibold ${tab === id ? "bg-blue-50 text-blue-700" : "text-slate-500 hover:bg-slate-50"}`} onClick={() => { setTab(id); setConfirmation(""); }}>{label}</button>)}</nav>
      {message ? <p role="status" className="mb-4 rounded-lg border border-blue-100 bg-blue-50 p-3 text-sm text-blue-900">{message}</p> : null}
      {confirmation ? <section className="mb-4 rounded-xl border border-amber-200 bg-amber-50 p-4"><h3 className="font-bold">{labels[confirmation]}?</h3><p className="mt-2 text-sm leading-6">{details[confirmation]}</p><p className="mt-2 break-all text-sm font-semibold">{student.email || student.phone}</p>{["grant","revoke"].includes(confirmation) ? <ul className="mt-2 list-inside list-disc text-sm">{selected.map((slug) => <li key={slug}>{courses.find((c) => c.slug === slug)?.title || slug}</li>)}</ul> : null}<div className="mt-4 flex gap-2"><button type="button" disabled={Boolean(pending)} onClick={() => void run(confirmation)} className="rounded-lg bg-blue-600 px-4 py-2 text-sm font-semibold text-white hover:bg-blue-700 disabled:opacity-50">{pending ? "Đang xử lý…" : "Xác nhận"}</button><button type="button" disabled={Boolean(pending)} className={buttonClass} onClick={() => setConfirmation("")}>Hủy</button></div></section> : null}
      {tab === "overview" ? <dl className="space-y-4 text-sm"><div><dt className="text-xs text-slate-500">Thanh toán</dt><dd className="mt-1">{student.paymentStatus}</dd></div><div><dt className="text-xs text-slate-500">Khóa đã đăng ký</dt><dd className="mt-1 space-y-1">{student.courseTitles.length ? student.courseTitles.map((title) => <p key={title}>{title}</p>) : "Chưa có khóa"}</dd></div><div><dt className="text-xs text-slate-500">Tiến độ học</dt><dd className="mt-1">{student.progressPercent}% · {student.progressNote}</dd></div><div><dt className="text-xs text-slate-500">Nguồn</dt><dd className="mt-1 break-words">{student.source || "—"}</dd></div><div><dt className="text-xs text-slate-500">Ghi chú hiện có</dt><dd className="mt-1 whitespace-pre-wrap break-words">{student.note || "Chưa có ghi chú"}</dd></div></dl> : null}
      {tab === "access" ? <section><p className="mb-3 text-sm text-slate-500">Chọn các khóa cần thao tác. Quyền hiện tại được ghi bên cạnh từng khóa.</p><div className="max-h-80 space-y-2 overflow-y-auto">{courses.map((course) => <label key={course.slug} className="flex items-start gap-3 rounded-lg border border-slate-200 p-3 text-sm"><input disabled={Boolean(pending) || Boolean(confirmation)} className="mt-1 size-4" type="checkbox" checked={selected.includes(course.slug)} onChange={() => setSelected((current) => current.includes(course.slug) ? current.filter((slug) => slug !== course.slug) : [...current, course.slug])} /><span className="min-w-0 flex-1 break-words">{course.title}<span className={`mt-1 block text-xs ${student.accessibleCourseSlugs?.includes(course.slug) ? "text-emerald-700" : "text-slate-400"}`}>{student.accessibleCourseSlugs?.includes(course.slug) ? "Đang có quyền học" : "Chưa có quyền học"}</span></span></label>)}</div><div className="mt-4 flex flex-wrap gap-2">{["grant","revoke"].map((action) => <button key={action} type="button" disabled={!student.email || !selected.length || Boolean(pending) || Boolean(confirmation)} onClick={() => setConfirmation(action)} className={action === "grant" ? "rounded-lg bg-blue-600 px-4 py-2 text-sm font-semibold text-white disabled:opacity-40" : buttonClass}>{action === "grant" ? "Cấp quyền" : "Thu quyền"}</button>)}</div>{!student.email ? <p className="mt-2 text-xs text-amber-700">Cần email để quản lý tài khoản và quyền học.</p> : null}</section> : null}
      {tab === "orders" ? <section><h3 className="mb-3 text-sm font-semibold">Mã đơn gắn với hồ sơ</h3>{[...student.paidOrderCodes.map((code) => ({code,status:"Đã thanh toán"})), ...student.pendingOrderCodes.map((code) => ({code,status:"Chưa thanh toán"}))].map(({code,status}) => <div key={code} className="flex flex-wrap justify-between gap-2 border-b border-slate-100 py-3 text-sm"><code>{code}</code><span className="text-slate-500">{status}</span></div>)}{!student.paidOrderCodes.length && !student.pendingOrderCodes.length ? <p className="text-sm text-slate-500">Chưa có đơn hàng. Quyền được cấp thủ công không được tính là doanh thu.</p> : null}</section> : null}
      {tab === "activity" ? student.email ? <StudentActivityTimeline studentEmail={student.email} /> : <p className="text-sm text-slate-500">Chưa có email để đối chiếu hoạt động học.</p> : null}
      {tab === "account" ? <section className="space-y-4">{accountError ? <p role="alert" className="text-sm text-amber-700">{accountError} <button type="button" className="font-semibold underline" onClick={() => setReload((x) => x + 1)}>Tải lại</button></p> : <p className="flex items-center gap-2 text-sm font-semibold">{account?.blocked ? <ShieldBan className="size-5 text-rose-600" /> : <ShieldCheck className="size-5 text-blue-600" />}{!student.email ? "Chưa có email" : !account ? "Đang kiểm tra tài khoản…" : account.blocked ? "Đang chặn đăng nhập" : account.exists ? "Tài khoản đang hoạt động" : "Chưa có tài khoản đăng nhập"}</p>}
        <button type="button" disabled={!student.email || !account?.exists || account.protected || Boolean(pending) || Boolean(confirmation)} className={buttonClass} onClick={() => setConfirmation("password")}>Cấp lại mật khẩu qua email</button>
        {canManageAccount ? <div className="space-y-3 border-t border-slate-200 pt-4"><button type="button" disabled={!account?.exists || account.protected || Boolean(pending) || Boolean(confirmation)} className={buttonClass} onClick={() => setConfirmation(account?.blocked ? "unblock" : "block")}>{account?.blocked ? "Mở lại đăng nhập" : "Chặn đăng nhập"}</button><div><button type="button" disabled={(!student.email && !student.phone) || Boolean(student.email && (!account || account.protected)) || Boolean(pending) || Boolean(confirmation)} className="rounded-lg border border-rose-200 px-3 py-2 text-sm font-semibold text-rose-700 disabled:opacity-40" onClick={() => setConfirmation("delete")}>Xóa hồ sơ…</button></div>{account?.protected ? <p className="text-xs text-slate-500">Tài khoản quản trị được quản lý tại Cài đặt → Thành viên.</p> : null}</div> : null}
      </section> : null}
    </div>
  </div>;
}
