export const categories=[{id:'all',name:'Tất cả Agent',color:'#7f8f7d'},{id:'business',name:'Điều phối',color:'#69b398'},{id:'research',name:'Nghiên cứu',color:'#a283d0'},{id:'marketing',name:'Marketing',color:'#dbb15e'},{id:'creative',name:'Sáng tạo',color:'#ed9889'},{id:'ads',name:'Quảng cáo',color:'#7bace0'},{id:'publish',name:'Đăng bài',color:'#72b6ba'}];
export const icons: Record<string,string>={brief:'<rect x="4" y="6" width="16" height="15" rx="2"/><path d="M9 6V3h6v3M8 11h8M8 15h5"/>',search:'<circle cx="10" cy="10" r="6"/><path d="m15 15 6 6M7 10h6M10 7v6"/>',plan:'<path d="M4 20V9m8 11V4m8 16v-7M2 20h20"/>',pen:'<path d="m4 16 12-12 4 4L8 20H4v-4ZM13 7l4 4"/>',design:'<rect x="3" y="3" width="18" height="18" rx="3"/><circle cx="9" cy="9" r="2"/><path d="m3 17 6-5 4 4 3-3 5 5"/>',code:'<path d="m8 6-6 6 6 6m8-12 6 6-6 6m-3-15-2 18"/>',ads:'<path d="m3 10 14-6v16L3 14v-4ZM6 15l2 6h4l-3-5M20 9l2-1m-2 7 2 1"/>',report:'<path d="M4 3v18h17M7 16l4-5 4 2 6-8"/>',video:'<rect x="2" y="5" width="15" height="14" rx="3"/><path d="m17 10 5-3v10l-5-3M8 9l4 3-4 3V9Z"/>',calendar:'<rect x="3" y="5" width="18" height="16" rx="3"/><path d="M7 2v6m10-6v6M3 11h18m-13 5 3 2 5-4"/>'};
export const agents=[
{id:'business-assistant',name:'Business Assistant',cat:'business',icon:'brief',colors:['#7ecab8','#51a994'],desc:'Gom thông tin doanh nghiệp, tạo brief chung và giao việc cho đúng Agent.',output:['Hồ sơ doanh nghiệp và tài sản hiện có.','Brief chung, danh sách công việc và Agent phụ trách.'],input:'Sản phẩm, khách hàng, mục tiêu và tài liệu doanh nghiệp hiện có.',permissions:'Quyền đọc thư mục hoặc tài liệu bạn chọn. Kiểm tra kết nối theo công việc; không cần cấp toàn bộ quyền.',prompt:'Giới thiệu các Agent và giúp tôi setup hồ sơ doanh nghiệp.'},
{id:'market-customer-research',name:'Nghiên cứu thị trường',cat:'research',icon:'search',colors:['#c493e7','#8a78ce'],desc:'Tìm hiểu thị trường, đối thủ và khách hàng từ nguồn có thể kiểm chứng.',output:['Phân khúc khách hàng, chân dung và hành trình mua.','Bản đồ đối thủ, insight và nguồn bằng chứng.'],input:'Ngành hàng, sản phẩm, thị trường và câu hỏi cần nghiên cứu.',permissions:'Truy cập nguồn công khai; tài liệu nội bộ chỉ đọc khi bạn cung cấp quyền.',prompt:'Nghiên cứu thị trường và khách hàng cho sản phẩm này.'},
{id:'marketing',name:'Marketing',cat:'marketing',icon:'plan',colors:['#e4c778','#d6a852'],desc:'Chuyển nghiên cứu và mục tiêu kinh doanh thành kế hoạch có thể triển khai.',output:['Kế hoạch marketing, phễu và lịch nội dung.','Ngân sách, KPI dự kiến và brief bàn giao.'],input:'Mục tiêu, sản phẩm, ngân sách và nghiên cứu đã được kiểm chứng hoặc phần thiếu được bạn chấp nhận.',permissions:'Tài liệu kinh doanh và nơi lưu kế hoạch. Không tự tạo hoặc sửa quảng cáo.',prompt:'Lập kế hoạch marketing từ nghiên cứu và mục tiêu tôi cung cấp.'},
{id:'content',name:'Content',cat:'creative',icon:'pen',colors:['#edb98c','#dd8a82'],desc:'Viết bài, caption, quảng cáo và kịch bản theo brief, giọng thương hiệu đã duyệt.',output:['Bài viết, caption, headline và hook.','Kịch bản chữ cùng biến thể có kiểm tra claim và giọng viết.'],input:'Brief, mục tiêu nội dung, giọng thương hiệu và bằng chứng cho các thông tin đưa vào bài.',permissions:'Quyền đọc brief và tài sản bạn chọn. Viết nội dung không cần quyền đăng bài.',prompt:'Viết nội dung theo brief và giọng thương hiệu này.'},
{id:'design',name:'Design',cat:'creative',icon:'design',colors:['#ec9ca7','#d87896'],desc:'Tạo định hướng hình ảnh, brief thiết kế và prompt cho bộ nội dung của bạn.',output:['Creative brief, danh sách asset và hướng bố cục.','Prompt hình ảnh, bàn giao thiết kế và kiểm tra visual.'],input:'Nội dung đã duyệt, nhận diện thương hiệu, kích thước và tài sản được phép sử dụng.',permissions:'Đọc asset; kết nối công cụ hình ảnh hoặc thiết kế khi tác vụ cần và công cụ khả dụng.',prompt:'Tạo brief thiết kế cho bộ nội dung đã duyệt này.'},
{id:'video',name:'Video',cat:'creative',icon:'video',colors:['#9b98e8','#7679c5'],desc:'Dựng cảnh, giọng đọc, phụ đề và chuyển động; xem trước và xuất video.',output:['Storyboard và bản xem trước.','MP4 sau khi render và kiểm tra hình, âm thanh, phụ đề.'],input:'Kịch bản đã duyệt, ảnh hoặc video, giọng đọc, tỷ lệ và thời lượng mong muốn.',permissions:'Video Studio kèm kit cần Node.js từ 22.12. Kiểm tra từng dịch vụ trước khi dùng; khóa dịch vụ do bạn nhập trong Settings cục bộ.',prompt:'Dựng video từ kịch bản và tài sản này, cho tôi xem trước khi xuất MP4.'},
{id:'web-landing',name:'Web / Landing Page',cat:'creative',icon:'code',colors:['#80b7ca','#6996b9'],desc:'Tạo trang xem trước, kiểm tra bố cục và tích hợp với website đã xác minh.',output:['Bản xem trước theo nội dung và hình ảnh đã duyệt.','Kết quả kiểm tra giao diện và hồ sơ bàn giao triển khai.'],input:'Nội dung, hình ảnh, trang tham khảo và chức năng cần có.',permissions:'Thư mục dự án cho bản xem trước. Đưa lên website thật cần đúng dự án, môi trường và quyền triển khai riêng.',prompt:'Tạo bản xem trước trang này từ nội dung và hình ảnh tôi cung cấp.'},
{id:'ads-setup',name:'Ads Setup',cat:'ads',icon:'ads',colors:['#82b6e5','#608fc6'],desc:'Thiết lập quảng cáo từ cấu hình đã chốt, kiểm tra và đọc lại trạng thái.',output:['Chiến dịch theo mục tiêu, ngân sách và tài sản đã duyệt.','ID, trạng thái xác minh và nhật ký thay đổi.'],input:'Tài khoản, Page, mục tiêu, ngân sách, tệp và content/media được duyệt.',permissions:'Facebook MCP phải hỗ trợ đầy đủ tác vụ. Quyền đọc, sửa, bật/tắt và xuất bản được xác nhận theo phạm vi; thiếu chức năng sẽ được báo rõ.',prompt:'Chạy quảng cáo bài này theo mục tiêu và ngân sách tôi cung cấp.'},
{id:'ads-report',name:'Ads Report',cat:'ads',icon:'report',colors:['#78bfc1','#5c9baf'],desc:'Đọc số liệu, đối chiếu thay đổi và chỉ ra phần cần tối ưu có bằng chứng.',output:['Dashboard và báo cáo theo giai đoạn.','Phân tích biến động và đề xuất cho Ads Setup.'],input:'Tài khoản, khoảng thời gian, KPI và nhật ký thay đổi quảng cáo.',permissions:'Quyền đọc số liệu và nhật ký; quyền lưu báo cáo khi bạn chọn nơi lưu. Không tự sửa chiến dịch.',prompt:'Báo cáo quảng cáo trong khoảng thời gian này và đề xuất tối ưu.'},
{id:'facebook-publisher',name:'Facebook Publisher',cat:'publish',icon:'calendar',colors:['#82c4a9','#57a692'],desc:'Nhận content và media, lên lịch Fanpage, báo tình trạng qua Google Sheets.',output:['Bài organic được lên lịch và kiểm tra từng bài.','Google Sheets: Ngày – Content – Hình ảnh – Giờ đăng – Tình trạng.'],input:'Link hoặc folder content/media, Fanpage, ngày, giờ và múi giờ đăng.',permissions:'Computer Use trong Meta Business Suite, quyền quản lý nội dung đúng Page và quyền ghi Google Sheets. Xác nhận lịch trước khi thực hiện.',prompt:'Lên lịch các bài trong folder này; hỏi tôi từng thông tin còn thiếu.'}
];
