"use client";
import { useState } from "react";
import catalog from "@/data/agent-library-packages.json";
import resources from "@/data/agent-library-resources.json";
const packages = [...catalog.agents, ...resources.resources];
const hash=async(data:ArrayBuffer)=>Array.from(new Uint8Array(await crypto.subtle.digest("SHA-256",data)),b=>b.toString(16).padStart(2,"0")).join("");
export function AgentPackageUpload(){
 const [busy,setBusy]=useState(false),[results,setResults]=useState<Record<string,string>>({});
 const status=(name:string,value:string)=>setResults(old=>({...old,[name]:value}));
 async function sign(slug:string,action:string){const response=await fetch("/api/admin/agent-library/upload",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({slug,action})});const data=await response.json();if(!response.ok||!data.url)throw new Error(data.message||"Chưa xử lý được gói.");return data.url as string;}
 async function verify(entry:typeof packages[number]){const url=await sign(entry.slug,"verify"),res=await fetch(url,{cache:"no-store",referrerPolicy:"no-referrer"});if(!res.ok)throw new Error("Chưa đọc được gói đã tải lên.");const bytes=await res.arrayBuffer();if(bytes.byteLength!==entry.size_bytes||await hash(bytes)!==entry.sha256)throw new Error("Gói trên kho không khớp SHA-256.");}
 async function upload(files:FileList|null){if(!files)return;setBusy(true);try{for(const file of Array.from(files)){const entry=packages.find(a=>a.filename===file.name);if(!entry){status(file.name,"Tên file không thuộc phiên bản này.");continue;}try{status(file.name,"Đang kiểm tra file…");if(file.size!==entry.size_bytes||await hash(await file.arrayBuffer())!==entry.sha256)throw new Error("File không khớp kích thước hoặc SHA-256.");try{await verify(entry);status(file.name,"Đã có · SHA-256 khớp");continue;}catch{/* A missing object can be uploaded; existing objects cannot be overwritten. */}status(file.name,"Đang tải lên…");const url=await sign(entry.slug,"upload");const form=new FormData();form.append("cacheControl","3600");form.append("",file);const res=await fetch(url,{method:"PUT",body:form,referrerPolicy:"no-referrer"});if(!res.ok)throw new Error("Tải lên chưa thành công; gói cũ được giữ nguyên.");status(file.name,"Đang kiểm tra trên kho…");await verify(entry);status(file.name,"Đã tải lên · SHA-256 khớp");}catch(error){status(file.name,error instanceof Error?error.message:"Có lỗi.");}}}finally{setBusy(false);}}
 async function verifyAll(){setBusy(true);try{for(const entry of packages){status(entry.filename,"Đang kiểm tra trên kho…");try{await verify(entry);status(entry.filename,"Đã xác minh trên kho · SHA-256 khớp");}catch(error){status(entry.filename,error instanceof Error?error.message:"Chưa xác minh được.");}}}finally{setBusy(false);}}
 return <main className="mx-auto max-w-4xl p-8"><h1 className="text-2xl font-bold">Quản lý gói Agent</h1><p className="my-4">Chọn các gói ZIP hoặc prompt TXT của phiên bản {catalog.version}. Mỗi file được đối chiếu trước và sau khi tải lên kho riêng.</p><input aria-label="Chọn gói Agent ZIP hoặc prompt TXT" type="file" accept=".zip,.txt" multiple disabled={busy} onChange={e=>upload(e.target.files)}/><button className="ml-4 rounded border px-4 py-2" disabled={busy} onClick={verifyAll}>Kiểm tra tất cả gói</button><p role="status" className="my-4">{busy?"Đang xử lý…":""}</p><ul className="space-y-3">{packages.map(a=><li key={a.slug}><strong>{a.name}</strong><div>{a.filename}</div><div>{results[a.filename]||"Chưa kiểm tra"}</div></li>)}</ul>{Object.entries(results).filter(([name])=>!packages.some(a=>a.filename===name)).map(([name,value])=><p key={name}>{name}: {value}</p>)}</main>;
}
